<!--
  Generated by WhyML - Tom Sapletta ' Embedded System Software & Hardware Developer, Germany Essen
  Description: Hardware and Software Development by Tom Sapletta. I share here my ideas, tests, solutions and opinions. I am develop software in PHP7, Python, NodeJS, JavaScript, Java on Windows, Linux, Android. I am inventor of products in embedded systems as IoT and smart products.
-->

<template>
  <article id="post-4038" class="col-sm-12 col-md-6 col-lg-4 col-xl-3 wpb_column home post-4038 post type-post status-publish format-standard has-post-thumbnail hentry category-kariera tag-debugowanie tag-frustracja tag-kariera tag-programowanie">
    <a href="https://tom.sapletta.pl/kariera/%f0%9f%a4%94-jak-radzicie-sobie-z-frustracja-w-pracy-developera/">
      <img src="https://tom.sapletta.pl/wp-content/uploads/2024/11/Screenshot-from-2024-11-24-13-52-03-960x964.png" :style="&#x27;z-index: 11;
						width: 220px;
						position: absolute;
						top: 0;
						right: 0px;
						border: 1px solid #444;&#x27;"></img>
      <div class="post imagebg standard-height scrim" :style="&#x27;background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/11/Screenshot-from-2024-11-24-13-52-03-960x964.png);&#x27;">
        <div class="stick-to-bottom">
          <h5 class="type--uppercase">
            <a href="https://tom.sapletta.pl/category/kariera/">Kariera</a>
          </h5>
          <h3>
            <a href="https://tom.sapletta.pl/kariera/%f0%9f%a4%94-jak-radzicie-sobie-z-frustracja-w-pracy-developera/">🤔 Jak radzicie sobie z frustracją w pracy developera?</a>
          </h3>
          <p>Po 2 dekadach latach w branży IT zauważyłem, że to temat, o którym mówimy za mało.</p>
          <a href="https://tom.sapletta.pl/kariera/%f0%9f%a4%94-jak-radzicie-sobie-z-frustracja-w-pracy-developera/">Continue Reading   →</a>
        </div>
      </div>
    </a>
  </article>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'TomSaplettaEmbeddedSystemSoftwareHardwareDeveloperGermanyEssen',
  setup() {
    return {};
  }
});
</script>

<style scoped>
.img-element-0 {
  z-index: 11;
  width: 220px;
  position: absolute;
  top: 0;
  right: 0px;
  border: 1px solid #444;
}
.div-element-1 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/11/Screenshot-from-2024-11-24-13-52-03-960x964.png);
}
.div-element-3 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/07/7lryofj0h9s-960x640.jpg);
}
.div-element-5 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2023/09/Internet_Service_1694329885.png);
}
.div-element-7 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/05/g7137ac243dedd7370e1c480a24647108df961d66086b7de86d90559cc0bab7d7ab3b9d9ee26d8dfb0bdc851bf8f5f2c5_640.jpg);
}
.div-element-9 {
  background-image: url(https://images.unsplash.com/photo-1555421689-d68471e189f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMjA3fDB8MXxzZWFyY2h8N3x8c3RhcnR1cCUyMHNhYXN8ZW58MHx8fHwxNzA1MDUzNzk2fDA&ixlib=rb-4.0.3&q=80&w=1200);
}
.div-element-11 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2023/10/mxvkwpijals.jpg);
}
.div-element-13 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/07/wd1lrb9oeeo-960x720.jpg);
}
.div-element-15 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2023/09/qzeno_gq7qa-960x640.jpg);
}
.div-element-17 {
  background-image: url(https://images.unsplash.com/photo-1558494949-ef010cbdcc31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8c2VydmVyLDE4MzMuODAxMDk2NTI2Mjc0fHx8fHx8MTY4ODM2NjE2NA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080);
}
.div-element-19 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2023/06/04x1yp9hnh8-960x640.jpg);
}
.div-element-21 {
  background-image: url(https://images.unsplash.com/photo-1655635949352-4343460d9211?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8QUksMTAzNS44NDIwNzMwNjkxNDc1fHx8fHx8MTY1ODQ5Mzk3MA&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080);
}
.div-element-23 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2022/02/ssq-front.jpg);
}
.div-element-25 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2021/10/firefox_2021-10-18_03-34-50.png);
}
.div-element-27 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2021/08/lenovo-yoga-7-ryzen-9-and-wifi-problem-on-linux1.jpg);
}
.div-element-29 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/09/kontekst-i-perspektywa-zamiast-burzy-bezmozgow.jpg);
}
.div-element-31 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/07/Automatycznie-zapisany-szkic.png);
}
.div-element-33 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/dlaczego-firmyorganizacje-upadają.jpg);
}
.div-element-35 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/spotkania-kształcą.jpg);
}
.div-element-37 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/jaka-jest-cena-wolności-w-czasie-kryzysu.jpg);
}
.div-element-39 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/pozytywne-skutki-kryzysu-2020-paniki-i-propagandy.jpg);
}
.div-element-41 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/teraz-ja-czyli-pytania-do-pracodawcy.jpg);
}
.div-element-43 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/jestesmy-fabryka.jpg);
}
.div-element-45 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/02/frontend-nie-dziękuję.jpg);
}
.div-element-47 {
  background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/02/droga-developera-pomiędzy-technologiami1.jpg);
}
.aside-moove-gdpr-cookie-info-bar {
  display: none;
}
.svg-element-50 {
  max-width: 30px;
  max-height: 30px;
}
.div-strict-necessary-cookies {
  display:none;
}
.div-element-52 {
  margin-top: 10px;
}
.wp-block-file--button {
  background:#32373c;
  color:#fff;
  text-decoration:none;
}
.is-layout-flex {
  flex-wrap: wrap;
  align-items: center;
}
.has-black-color {
  color: var(--wp--preset--color--black) !important;
}
.has-cyan-bluish-gray-color {
  color: var(--wp--preset--color--cyan-bluish-gray) !important;
}
.has-white-color {
  color: var(--wp--preset--color--white) !important;
}
.has-pale-pink-color {
  color: var(--wp--preset--color--pale-pink) !important;
}
.has-vivid-red-color {
  color: var(--wp--preset--color--vivid-red) !important;
}
.has-luminous-vivid-orange-color {
  color: var(--wp--preset--color--luminous-vivid-orange) !important;
}
.has-luminous-vivid-amber-color {
  color: var(--wp--preset--color--luminous-vivid-amber) !important;
}
.has-light-green-cyan-color {
  color: var(--wp--preset--color--light-green-cyan) !important;
}
.has-vivid-green-cyan-color {
  color: var(--wp--preset--color--vivid-green-cyan) !important;
}
.has-pale-cyan-blue-color {
  color: var(--wp--preset--color--pale-cyan-blue) !important;
}
.has-vivid-cyan-blue-color {
  color: var(--wp--preset--color--vivid-cyan-blue) !important;
}
.has-vivid-purple-color {
  color: var(--wp--preset--color--vivid-purple) !important;
}
.has-black-background-color {
  background-color: var(--wp--preset--color--black) !important;
}
.has-cyan-bluish-gray-background-color {
  background-color: var(--wp--preset--color--cyan-bluish-gray) !important;
}
.has-white-background-color {
  background-color: var(--wp--preset--color--white) !important;
}
.has-pale-pink-background-color {
  background-color: var(--wp--preset--color--pale-pink) !important;
}
.has-vivid-red-background-color {
  background-color: var(--wp--preset--color--vivid-red) !important;
}
.has-luminous-vivid-orange-background-color {
  background-color: var(--wp--preset--color--luminous-vivid-orange) !important;
}
.has-luminous-vivid-amber-background-color {
  background-color: var(--wp--preset--color--luminous-vivid-amber) !important;
}
.has-light-green-cyan-background-color {
  background-color: var(--wp--preset--color--light-green-cyan) !important;
}
.has-vivid-green-cyan-background-color {
  background-color: var(--wp--preset--color--vivid-green-cyan) !important;
}
.has-pale-cyan-blue-background-color {
  background-color: var(--wp--preset--color--pale-cyan-blue) !important;
}
.has-vivid-cyan-blue-background-color {
  background-color: var(--wp--preset--color--vivid-cyan-blue) !important;
}
.has-vivid-purple-background-color {
  background-color: var(--wp--preset--color--vivid-purple) !important;
}
.has-black-border-color {
  border-color: var(--wp--preset--color--black) !important;
}
.has-cyan-bluish-gray-border-color {
  border-color: var(--wp--preset--color--cyan-bluish-gray) !important;
}
.has-white-border-color {
  border-color: var(--wp--preset--color--white) !important;
}
.has-pale-pink-border-color {
  border-color: var(--wp--preset--color--pale-pink) !important;
}
.has-vivid-red-border-color {
  border-color: var(--wp--preset--color--vivid-red) !important;
}
.has-luminous-vivid-orange-border-color {
  border-color: var(--wp--preset--color--luminous-vivid-orange) !important;
}
.has-luminous-vivid-amber-border-color {
  border-color: var(--wp--preset--color--luminous-vivid-amber) !important;
}
.has-light-green-cyan-border-color {
  border-color: var(--wp--preset--color--light-green-cyan) !important;
}
.has-vivid-green-cyan-border-color {
  border-color: var(--wp--preset--color--vivid-green-cyan) !important;
}
.has-pale-cyan-blue-border-color {
  border-color: var(--wp--preset--color--pale-cyan-blue) !important;
}
.has-vivid-cyan-blue-border-color {
  border-color: var(--wp--preset--color--vivid-cyan-blue) !important;
}
.has-vivid-purple-border-color {
  border-color: var(--wp--preset--color--vivid-purple) !important;
}
.has-vivid-cyan-blue-to-vivid-purple-gradient-background {
  background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;
}
.has-light-green-cyan-to-vivid-green-cyan-gradient-background {
  background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;
}
.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background {
  background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;
}
.has-luminous-vivid-orange-to-vivid-red-gradient-background {
  background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important;
}
.has-very-light-gray-to-cyan-bluish-gray-gradient-background {
  background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important;
}
.has-cool-to-warm-spectrum-gradient-background {
  background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important;
}
.has-blush-light-purple-gradient-background {
  background: var(--wp--preset--gradient--blush-light-purple) !important;
}
.has-blush-bordeaux-gradient-background {
  background: var(--wp--preset--gradient--blush-bordeaux) !important;
}
.has-luminous-dusk-gradient-background {
  background: var(--wp--preset--gradient--luminous-dusk) !important;
}
.has-pale-ocean-gradient-background {
  background: var(--wp--preset--gradient--pale-ocean) !important;
}
.has-electric-grass-gradient-background {
  background: var(--wp--preset--gradient--electric-grass) !important;
}
.has-midnight-gradient-background {
  background: var(--wp--preset--gradient--midnight) !important;
}
.has-small-font-size {
  font-size: var(--wp--preset--font-size--small) !important;
}
.has-medium-font-size {
  font-size: var(--wp--preset--font-size--medium) !important;
}
.has-large-font-size {
  font-size: var(--wp--preset--font-size--large) !important;
}
.has-x-large-font-size {
  font-size: var(--wp--preset--font-size--x-large) !important;
}
.ez-toc-container-direction {
  direction: ltr;
}
.ez-toc-counter-ul {
  counter-reset: item;
}
.social-icons-li-a-i {
  color: #bbb;
}
.hamburger {
  color: #ffffff;
}
.pulsate-css {
  border: 3px solid #666;
}
.stick-to-bottom {
  bottom: 15px;
  left: 15px;
  right: 5px;
  z-index: 2;
}
</style>