/**
 * Generated by WhyML - Example Domain
 * React Component
 */

import React from 'react';
import styles from './styles.module.css';

interface Props {
  className?: string;
  style?: React.CSSProperties;
}

const ExampleDomain: React.FC<Props> = (props) => {
    return (
      <div type="container" className="page-container">
<div type="heading">Example Domain</div>,
<div type="paragraph">This domain is for use in illustrative examples in documents. You may use this domain in literature without prior coordination or asking for permission.</div>,
<div type="paragraph">More information...</div>,
<div type="link" href="https://www.iana.org/domains/example">More information...</div>
</div>
    );
  };

  export default ExampleDomain;