<?php
/**
 * Generated by WhyML - Tom Sapletta ' Embedded System Software & Hardware Developer, Germany Essen
 * Description: Hardware and Software Development by Tom Sapletta. I share here my ideas, tests, solutions and opinions. I am develop software in PHP7, Python, NodeJS, JavaScript, Java on Windows, Linux, Android. I am inventor of products in embedded systems as IoT and smart products.
 * PHP Component Class
 */

<?php

namespace App\Components;

use InvalidArgumentException;
use RuntimeException;

/**
 * Hardware and Software Development by Tom Sapletta. I share here my ideas, tests, solutions and opinions. I am develop software in PHP7, Python, NodeJS, JavaScript, Java on Windows, Linux, Android. I am inventor of products in embedded systems as IoT and smart products.
 *
 * @version 1.0.0
 * @author WhyML Generator
 * @package App\Components
 */
class TomSaplettaEmbeddedSystemSoftwareHardwareDeveloperGermanyEssenComponent
{
    /**
     * Component data
     * @var array
     */
    private array $data = [];

    /**
     * Component styles
     * @var array
     */
    private array $styles = [
            'img_element_0' => 'z-index: 11; width: 220px; position: absolute; top: 0; right: 0px; border: 1px solid #444;',
            'div_element_1' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/11/Screenshot-from-2024-11-24-13-52-03-960x964.png);',
            'div_element_3' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/07/7lryofj0h9s-960x640.jpg);',
            'div_element_5' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2023/09/Internet_Service_1694329885.png);',
            'div_element_7' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/05/g7137ac243dedd7370e1c480a24647108df961d66086b7de86d90559cc0bab7d7ab3b9d9ee26d8dfb0bdc851bf8f5f2c5_640.jpg);',
            'div_element_9' => 'background-image: url(https://images.unsplash.com/photo-1555421689-d68471e189f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMjA3fDB8MXxzZWFyY2h8N3x8c3RhcnR1cCUyMHNhYXN8ZW58MHx8fHwxNzA1MDUzNzk2fDA&ixlib=rb-4.0.3&q=80&w=1200);',
            'div_element_11' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2023/10/mxvkwpijals.jpg);',
            'div_element_13' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/07/wd1lrb9oeeo-960x720.jpg);',
            'div_element_15' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2023/09/qzeno_gq7qa-960x640.jpg);',
            'div_element_17' => 'background-image: url(https://images.unsplash.com/photo-1558494949-ef010cbdcc31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8c2VydmVyLDE4MzMuODAxMDk2NTI2Mjc0fHx8fHx8MTY4ODM2NjE2NA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080);',
            'div_element_19' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2023/06/04x1yp9hnh8-960x640.jpg);',
            'div_element_21' => 'background-image: url(https://images.unsplash.com/photo-1655635949352-4343460d9211?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8QUksMTAzNS44NDIwNzMwNjkxNDc1fHx8fHx8MTY1ODQ5Mzk3MA&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080);',
            'div_element_23' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2022/02/ssq-front.jpg);',
            'div_element_25' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2021/10/firefox_2021-10-18_03-34-50.png);',
            'div_element_27' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2021/08/lenovo-yoga-7-ryzen-9-and-wifi-problem-on-linux1.jpg);',
            'div_element_29' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/09/kontekst-i-perspektywa-zamiast-burzy-bezmozgow.jpg);',
            'div_element_31' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/07/Automatycznie-zapisany-szkic.png);',
            'div_element_33' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/dlaczego-firmyorganizacje-upadają.jpg);',
            'div_element_35' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/spotkania-kształcą.jpg);',
            'div_element_37' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/jaka-jest-cena-wolności-w-czasie-kryzysu.jpg);',
            'div_element_39' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/pozytywne-skutki-kryzysu-2020-paniki-i-propagandy.jpg);',
            'div_element_41' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/teraz-ja-czyli-pytania-do-pracodawcy.jpg);',
            'div_element_43' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/jestesmy-fabryka.jpg);',
            'div_element_45' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/02/frontend-nie-dziękuję.jpg);',
            'div_element_47' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/02/droga-developera-pomiędzy-technologiami1.jpg);',
            'aside_moove_gdpr_cookie_info_bar' => 'display: none;',
            'svg_element_50' => 'max-width: 30px; max-height: 30px;',
            'div_strict_necessary_cookies' => 'display:none;',
            'div_element_52' => 'margin-top: 10px;',
            'wp_block_file__button' => 'background:#32373c; color:#fff; text-decoration:none;',
            'is_layout_flex' => 'flex-wrap: wrap; align-items: center;',
            'has_black_color' => 'color: var(--wp--preset--color--black) !important;',
            'has_cyan_bluish_gray_color' => 'color: var(--wp--preset--color--cyan-bluish-gray) !important;',
            'has_white_color' => 'color: var(--wp--preset--color--white) !important;',
            'has_pale_pink_color' => 'color: var(--wp--preset--color--pale-pink) !important;',
            'has_vivid_red_color' => 'color: var(--wp--preset--color--vivid-red) !important;',
            'has_luminous_vivid_orange_color' => 'color: var(--wp--preset--color--luminous-vivid-orange) !important;',
            'has_luminous_vivid_amber_color' => 'color: var(--wp--preset--color--luminous-vivid-amber) !important;',
            'has_light_green_cyan_color' => 'color: var(--wp--preset--color--light-green-cyan) !important;',
            'has_vivid_green_cyan_color' => 'color: var(--wp--preset--color--vivid-green-cyan) !important;',
            'has_pale_cyan_blue_color' => 'color: var(--wp--preset--color--pale-cyan-blue) !important;',
            'has_vivid_cyan_blue_color' => 'color: var(--wp--preset--color--vivid-cyan-blue) !important;',
            'has_vivid_purple_color' => 'color: var(--wp--preset--color--vivid-purple) !important;',
            'has_black_background_color' => 'background-color: var(--wp--preset--color--black) !important;',
            'has_cyan_bluish_gray_background_color' => 'background-color: var(--wp--preset--color--cyan-bluish-gray) !important;',
            'has_white_background_color' => 'background-color: var(--wp--preset--color--white) !important;',
            'has_pale_pink_background_color' => 'background-color: var(--wp--preset--color--pale-pink) !important;',
            'has_vivid_red_background_color' => 'background-color: var(--wp--preset--color--vivid-red) !important;',
            'has_luminous_vivid_orange_background_color' => 'background-color: var(--wp--preset--color--luminous-vivid-orange) !important;',
            'has_luminous_vivid_amber_background_color' => 'background-color: var(--wp--preset--color--luminous-vivid-amber) !important;',
            'has_light_green_cyan_background_color' => 'background-color: var(--wp--preset--color--light-green-cyan) !important;',
            'has_vivid_green_cyan_background_color' => 'background-color: var(--wp--preset--color--vivid-green-cyan) !important;',
            'has_pale_cyan_blue_background_color' => 'background-color: var(--wp--preset--color--pale-cyan-blue) !important;',
            'has_vivid_cyan_blue_background_color' => 'background-color: var(--wp--preset--color--vivid-cyan-blue) !important;',
            'has_vivid_purple_background_color' => 'background-color: var(--wp--preset--color--vivid-purple) !important;',
            'has_black_border_color' => 'border-color: var(--wp--preset--color--black) !important;',
            'has_cyan_bluish_gray_border_color' => 'border-color: var(--wp--preset--color--cyan-bluish-gray) !important;',
            'has_white_border_color' => 'border-color: var(--wp--preset--color--white) !important;',
            'has_pale_pink_border_color' => 'border-color: var(--wp--preset--color--pale-pink) !important;',
            'has_vivid_red_border_color' => 'border-color: var(--wp--preset--color--vivid-red) !important;',
            'has_luminous_vivid_orange_border_color' => 'border-color: var(--wp--preset--color--luminous-vivid-orange) !important;',
            'has_luminous_vivid_amber_border_color' => 'border-color: var(--wp--preset--color--luminous-vivid-amber) !important;',
            'has_light_green_cyan_border_color' => 'border-color: var(--wp--preset--color--light-green-cyan) !important;',
            'has_vivid_green_cyan_border_color' => 'border-color: var(--wp--preset--color--vivid-green-cyan) !important;',
            'has_pale_cyan_blue_border_color' => 'border-color: var(--wp--preset--color--pale-cyan-blue) !important;',
            'has_vivid_cyan_blue_border_color' => 'border-color: var(--wp--preset--color--vivid-cyan-blue) !important;',
            'has_vivid_purple_border_color' => 'border-color: var(--wp--preset--color--vivid-purple) !important;',
            'has_vivid_cyan_blue_to_vivid_purple_gradient_background' => 'background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;',
            'has_light_green_cyan_to_vivid_green_cyan_gradient_background' => 'background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;',
            'has_luminous_vivid_amber_to_luminous_vivid_orange_gradient_background' => 'background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;',
            'has_luminous_vivid_orange_to_vivid_red_gradient_background' => 'background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important;',
            'has_very_light_gray_to_cyan_bluish_gray_gradient_background' => 'background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important;',
            'has_cool_to_warm_spectrum_gradient_background' => 'background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important;',
            'has_blush_light_purple_gradient_background' => 'background: var(--wp--preset--gradient--blush-light-purple) !important;',
            'has_blush_bordeaux_gradient_background' => 'background: var(--wp--preset--gradient--blush-bordeaux) !important;',
            'has_luminous_dusk_gradient_background' => 'background: var(--wp--preset--gradient--luminous-dusk) !important;',
            'has_pale_ocean_gradient_background' => 'background: var(--wp--preset--gradient--pale-ocean) !important;',
            'has_electric_grass_gradient_background' => 'background: var(--wp--preset--gradient--electric-grass) !important;',
            'has_midnight_gradient_background' => 'background: var(--wp--preset--gradient--midnight) !important;',
            'has_small_font_size' => 'font-size: var(--wp--preset--font-size--small) !important;',
            'has_medium_font_size' => 'font-size: var(--wp--preset--font-size--medium) !important;',
            'has_large_font_size' => 'font-size: var(--wp--preset--font-size--large) !important;',
            'has_x_large_font_size' => 'font-size: var(--wp--preset--font-size--x-large) !important;',
            'ez_toc_container_direction' => 'direction: ltr;',
            'ez_toc_counter_ul' => 'counter-reset: item;',
            'social_icons_li_a_i' => 'color: #bbb;',
            'hamburger' => 'color: #ffffff;',
            'pulsate_css' => 'border: 3px solid #666;',
            'stick_to_bottom' => 'bottom: 15px; left: 15px; right: 5px; z-index: 2;'
        ];

    /**
     * Constructor
     * @param array $data Initial component data
     */
    public function __construct(array $data = []): void
    {
        $this->data = $data;
    }

    /**
     * Render the component
     * @return string HTML output
     */
    public function render(): string
    {
        $html = '';

        $html .= '<article' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['id' => 'post-4038', 'class' => 'col-sm-12 col-md-6 col-lg-4 col-xl-3 wpb_column home post-4038 post type-post status-publish format-standard has-post-thumbnail hentry category-kariera tag-debugowanie tag-frustracja tag-kariera tag-programowanie']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['href' => 'https://tom.sapletta.pl/kariera/%f0%9f%a4%94-jak-radzicie-sobie-z-frustracja-w-pracy-developera/']) . '>';
        $html .= '<img' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['src' => 'https://tom.sapletta.pl/wp-content/uploads/2024/11/Screenshot-from-2024-11-24-13-52-03-960x964.png', 'style' => 'z-index: 11;
						width: 220px;
						position: absolute;
						top: 0;
						right: 0px;
						border: 1px solid #444;']) . '></div>';
        $html .= '</img>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'post imagebg standard-height scrim', 'style' => 'background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/11/Screenshot-from-2024-11-24-13-52-03-960x964.png);']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'stick-to-bottom']) . '>';
        $html .= '<h5' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'type--uppercase']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['href' => 'https://tom.sapletta.pl/category/kariera/']) . '>' . $this->escapeHtml('Kariera') . '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</h5>';
        $html .= '<h3' . '' . '>';
        $html .= '<div' . '' . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['href' => 'https://tom.sapletta.pl/kariera/%f0%9f%a4%94-jak-radzicie-sobie-z-frustracja-w-pracy-developera/']) . '>' . $this->escapeHtml('🤔 Jak radzicie sobie z frustracją w pracy developera?') . '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</h3>';
        $html .= '<p' . '' . '>';
        $html .= '<div' . '' . '>' . $this->escapeHtml('Po 2 dekadach latach w branży IT zauważyłem, że to temat, o którym mówimy za mało.') . '</div>';
        $html .= '</p>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['href' => 'https://tom.sapletta.pl/kariera/%f0%9f%a4%94-jak-radzicie-sobie-z-frustracja-w-pracy-developera/']) . '>' . $this->escapeHtml('Continue Reading   →') . '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</article>';

        return $html;
    }

    /**
     * Get component styles as CSS
     * @return string CSS styles
     */
    public function getStyles(): string
    {
        $css = '';

        $css .= '.img_element_0 { z-index: 11; width: 220px; position: absolute; top: 0; right: 0px; border: 1px solid #444; }' . "\n";
        $css .= '.div_element_1 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/11/Screenshot-from-2024-11-24-13-52-03-960x964.png); }' . "\n";
        $css .= '.div_element_3 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/07/7lryofj0h9s-960x640.jpg); }' . "\n";
        $css .= '.div_element_5 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2023/09/Internet_Service_1694329885.png); }' . "\n";
        $css .= '.div_element_7 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/05/g7137ac243dedd7370e1c480a24647108df961d66086b7de86d90559cc0bab7d7ab3b9d9ee26d8dfb0bdc851bf8f5f2c5_640.jpg); }' . "\n";
        $css .= '.div_element_9 { background-image: url(https://images.unsplash.com/photo-1555421689-d68471e189f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMjA3fDB8MXxzZWFyY2h8N3x8c3RhcnR1cCUyMHNhYXN8ZW58MHx8fHwxNzA1MDUzNzk2fDA&ixlib=rb-4.0.3&q=80&w=1200); }' . "\n";
        $css .= '.div_element_11 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2023/10/mxvkwpijals.jpg); }' . "\n";
        $css .= '.div_element_13 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2024/07/wd1lrb9oeeo-960x720.jpg); }' . "\n";
        $css .= '.div_element_15 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2023/09/qzeno_gq7qa-960x640.jpg); }' . "\n";
        $css .= '.div_element_17 { background-image: url(https://images.unsplash.com/photo-1558494949-ef010cbdcc31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8c2VydmVyLDE4MzMuODAxMDk2NTI2Mjc0fHx8fHx8MTY4ODM2NjE2NA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080); }' . "\n";
        $css .= '.div_element_19 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2023/06/04x1yp9hnh8-960x640.jpg); }' . "\n";
        $css .= '.div_element_21 { background-image: url(https://images.unsplash.com/photo-1655635949352-4343460d9211?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8QUksMTAzNS44NDIwNzMwNjkxNDc1fHx8fHx8MTY1ODQ5Mzk3MA&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080); }' . "\n";
        $css .= '.div_element_23 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2022/02/ssq-front.jpg); }' . "\n";
        $css .= '.div_element_25 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2021/10/firefox_2021-10-18_03-34-50.png); }' . "\n";
        $css .= '.div_element_27 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2021/08/lenovo-yoga-7-ryzen-9-and-wifi-problem-on-linux1.jpg); }' . "\n";
        $css .= '.div_element_29 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/09/kontekst-i-perspektywa-zamiast-burzy-bezmozgow.jpg); }' . "\n";
        $css .= '.div_element_31 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/07/Automatycznie-zapisany-szkic.png); }' . "\n";
        $css .= '.div_element_33 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/dlaczego-firmyorganizacje-upadają.jpg); }' . "\n";
        $css .= '.div_element_35 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/spotkania-kształcą.jpg); }' . "\n";
        $css .= '.div_element_37 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/jaka-jest-cena-wolności-w-czasie-kryzysu.jpg); }' . "\n";
        $css .= '.div_element_39 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/pozytywne-skutki-kryzysu-2020-paniki-i-propagandy.jpg); }' . "\n";
        $css .= '.div_element_41 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/teraz-ja-czyli-pytania-do-pracodawcy.jpg); }' . "\n";
        $css .= '.div_element_43 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/03/jestesmy-fabryka.jpg); }' . "\n";
        $css .= '.div_element_45 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/02/frontend-nie-dziękuję.jpg); }' . "\n";
        $css .= '.div_element_47 { background-image: url(https://tom.sapletta.pl/wp-content/uploads/2020/02/droga-developera-pomiędzy-technologiami1.jpg); }' . "\n";
        $css .= '.aside_moove_gdpr_cookie_info_bar { display: none; }' . "\n";
        $css .= '.svg_element_50 { max-width: 30px; max-height: 30px; }' . "\n";
        $css .= '.div_strict_necessary_cookies { display:none; }' . "\n";
        $css .= '.div_element_52 { margin-top: 10px; }' . "\n";
        $css .= '.wp_block_file__button { background:#32373c; color:#fff; text-decoration:none; }' . "\n";
        $css .= '.is_layout_flex { flex-wrap: wrap; align-items: center; }' . "\n";
        $css .= '.has_black_color { color: var(--wp--preset--color--black) !important; }' . "\n";
        $css .= '.has_cyan_bluish_gray_color { color: var(--wp--preset--color--cyan-bluish-gray) !important; }' . "\n";
        $css .= '.has_white_color { color: var(--wp--preset--color--white) !important; }' . "\n";
        $css .= '.has_pale_pink_color { color: var(--wp--preset--color--pale-pink) !important; }' . "\n";
        $css .= '.has_vivid_red_color { color: var(--wp--preset--color--vivid-red) !important; }' . "\n";
        $css .= '.has_luminous_vivid_orange_color { color: var(--wp--preset--color--luminous-vivid-orange) !important; }' . "\n";
        $css .= '.has_luminous_vivid_amber_color { color: var(--wp--preset--color--luminous-vivid-amber) !important; }' . "\n";
        $css .= '.has_light_green_cyan_color { color: var(--wp--preset--color--light-green-cyan) !important; }' . "\n";
        $css .= '.has_vivid_green_cyan_color { color: var(--wp--preset--color--vivid-green-cyan) !important; }' . "\n";
        $css .= '.has_pale_cyan_blue_color { color: var(--wp--preset--color--pale-cyan-blue) !important; }' . "\n";
        $css .= '.has_vivid_cyan_blue_color { color: var(--wp--preset--color--vivid-cyan-blue) !important; }' . "\n";
        $css .= '.has_vivid_purple_color { color: var(--wp--preset--color--vivid-purple) !important; }' . "\n";
        $css .= '.has_black_background_color { background-color: var(--wp--preset--color--black) !important; }' . "\n";
        $css .= '.has_cyan_bluish_gray_background_color { background-color: var(--wp--preset--color--cyan-bluish-gray) !important; }' . "\n";
        $css .= '.has_white_background_color { background-color: var(--wp--preset--color--white) !important; }' . "\n";
        $css .= '.has_pale_pink_background_color { background-color: var(--wp--preset--color--pale-pink) !important; }' . "\n";
        $css .= '.has_vivid_red_background_color { background-color: var(--wp--preset--color--vivid-red) !important; }' . "\n";
        $css .= '.has_luminous_vivid_orange_background_color { background-color: var(--wp--preset--color--luminous-vivid-orange) !important; }' . "\n";
        $css .= '.has_luminous_vivid_amber_background_color { background-color: var(--wp--preset--color--luminous-vivid-amber) !important; }' . "\n";
        $css .= '.has_light_green_cyan_background_color { background-color: var(--wp--preset--color--light-green-cyan) !important; }' . "\n";
        $css .= '.has_vivid_green_cyan_background_color { background-color: var(--wp--preset--color--vivid-green-cyan) !important; }' . "\n";
        $css .= '.has_pale_cyan_blue_background_color { background-color: var(--wp--preset--color--pale-cyan-blue) !important; }' . "\n";
        $css .= '.has_vivid_cyan_blue_background_color { background-color: var(--wp--preset--color--vivid-cyan-blue) !important; }' . "\n";
        $css .= '.has_vivid_purple_background_color { background-color: var(--wp--preset--color--vivid-purple) !important; }' . "\n";
        $css .= '.has_black_border_color { border-color: var(--wp--preset--color--black) !important; }' . "\n";
        $css .= '.has_cyan_bluish_gray_border_color { border-color: var(--wp--preset--color--cyan-bluish-gray) !important; }' . "\n";
        $css .= '.has_white_border_color { border-color: var(--wp--preset--color--white) !important; }' . "\n";
        $css .= '.has_pale_pink_border_color { border-color: var(--wp--preset--color--pale-pink) !important; }' . "\n";
        $css .= '.has_vivid_red_border_color { border-color: var(--wp--preset--color--vivid-red) !important; }' . "\n";
        $css .= '.has_luminous_vivid_orange_border_color { border-color: var(--wp--preset--color--luminous-vivid-orange) !important; }' . "\n";
        $css .= '.has_luminous_vivid_amber_border_color { border-color: var(--wp--preset--color--luminous-vivid-amber) !important; }' . "\n";
        $css .= '.has_light_green_cyan_border_color { border-color: var(--wp--preset--color--light-green-cyan) !important; }' . "\n";
        $css .= '.has_vivid_green_cyan_border_color { border-color: var(--wp--preset--color--vivid-green-cyan) !important; }' . "\n";
        $css .= '.has_pale_cyan_blue_border_color { border-color: var(--wp--preset--color--pale-cyan-blue) !important; }' . "\n";
        $css .= '.has_vivid_cyan_blue_border_color { border-color: var(--wp--preset--color--vivid-cyan-blue) !important; }' . "\n";
        $css .= '.has_vivid_purple_border_color { border-color: var(--wp--preset--color--vivid-purple) !important; }' . "\n";
        $css .= '.has_vivid_cyan_blue_to_vivid_purple_gradient_background { background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important; }' . "\n";
        $css .= '.has_light_green_cyan_to_vivid_green_cyan_gradient_background { background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important; }' . "\n";
        $css .= '.has_luminous_vivid_amber_to_luminous_vivid_orange_gradient_background { background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important; }' . "\n";
        $css .= '.has_luminous_vivid_orange_to_vivid_red_gradient_background { background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important; }' . "\n";
        $css .= '.has_very_light_gray_to_cyan_bluish_gray_gradient_background { background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important; }' . "\n";
        $css .= '.has_cool_to_warm_spectrum_gradient_background { background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important; }' . "\n";
        $css .= '.has_blush_light_purple_gradient_background { background: var(--wp--preset--gradient--blush-light-purple) !important; }' . "\n";
        $css .= '.has_blush_bordeaux_gradient_background { background: var(--wp--preset--gradient--blush-bordeaux) !important; }' . "\n";
        $css .= '.has_luminous_dusk_gradient_background { background: var(--wp--preset--gradient--luminous-dusk) !important; }' . "\n";
        $css .= '.has_pale_ocean_gradient_background { background: var(--wp--preset--gradient--pale-ocean) !important; }' . "\n";
        $css .= '.has_electric_grass_gradient_background { background: var(--wp--preset--gradient--electric-grass) !important; }' . "\n";
        $css .= '.has_midnight_gradient_background { background: var(--wp--preset--gradient--midnight) !important; }' . "\n";
        $css .= '.has_small_font_size { font-size: var(--wp--preset--font-size--small) !important; }' . "\n";
        $css .= '.has_medium_font_size { font-size: var(--wp--preset--font-size--medium) !important; }' . "\n";
        $css .= '.has_large_font_size { font-size: var(--wp--preset--font-size--large) !important; }' . "\n";
        $css .= '.has_x_large_font_size { font-size: var(--wp--preset--font-size--x-large) !important; }' . "\n";
        $css .= '.ez_toc_container_direction { direction: ltr; }' . "\n";
        $css .= '.ez_toc_counter_ul { counter-reset: item; }' . "\n";
        $css .= '.social_icons_li_a_i { color: #bbb; }' . "\n";
        $css .= '.hamburger { color: #ffffff; }' . "\n";
        $css .= '.pulsate_css { border: 3px solid #666; }' . "\n";
        $css .= '.stick_to_bottom { bottom: 15px; left: 15px; right: 5px; z-index: 2; }' . "\n";

        return $css;
    }

    /**
     * Set component data
     * @param string $key Data key
     * @param mixed $value Data value
     * @return self
     */
    public function setData(string $key, mixed $value): self
    {
        $this->data[$key] = $value;
        return $this;
    }

    /**
     * Get component data
     * @param string $key Data key
     * @param mixed $default Default value
     * @return mixed
     */
    public function getData(string $key, mixed $default = null): mixed
    {
        return $this->data[$key] ?? $default;
    }


    /**
     * Escape HTML content
     * @param string $content Content to escape
     * @return string Escaped content
     */
    private function escapeHtml(string $content): string
    {
        return htmlspecialchars($content, ENT_QUOTES | ENT_HTML5, 'UTF-8');
    }

    /**
     * Build HTML attributes string
     * @param array $attributes Attributes array
     * @return string Attributes string
     */
    private function buildAttributes(array $attributes): string
    {
        $attr = [];
        foreach ($attributes as $key => $value) {
            if ($value !== null && $value !== false) {
                $attr[] = $key . '="' . $this->escapeHtml($value) . '"';
            }
        }
        return empty($attr) ? '' : ' ' . implode(' ', $attr);
    }
}