<!--
  Generated by WhyML - WhyML Test App
  Description: Test application to verify WhyML functionality
-->

<template>
  <div>
    <div class="container">
      <h1>
        <div class="main-title">Welcome to WhyML Test App</div>
      </h1>
      <p>
        <div class="intro">This is a test application to verify WhyML CLI functionality works correctly.</div>
      </p>
      <div>
        <div class="features-section">
          <h2>
            <div class="section-title">Features</div>
          </h2>
          <ul>
            <div class="feature-list">
              <li>
                <div>CLI Commands</div>
              </li>
              <li>
                <div>Natural Language Conversion</div>
              </li>
              <li>
                <div>Application Generators</div>
              </li>
              <li>
                <div>Development Server</div>
              </li>
            </div>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'WhymlTestApp',
  setup() {
    return {};
  }
});
</script>

<style scoped>
.container {
  width: 100%;
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}
.main-title {
  color: #007acc;
  font-family: Helvetica, Arial, sans-serif;
  font-size: 32px;
}
.intro {
  font-family: Arial, sans-serif;
  color: #333;
  margin: 16px 0;
}
.section-title {
  color: #007acc;
  font-family: Helvetica, Arial, sans-serif;
  font-size: 24px;
  margin-top: 24px;
}
.feature-list {
  font-family: Arial, sans-serif;
  color: #333;
  padding-left: 20px;
}
.features-section {
  margin-top: 20px;
}
</style>