/**
 * Generated by WhyML - WhyML Test App
 * Description: Test application to verify WhyML functionality
 * React Component
 */

import React from 'react';
import styles from './styles.module.css';

interface Props {
  className?: string;
  style?: React.CSSProperties;
}

const WhymlTestApp: React.FC<Props> = (props) => {
    return (
      <div><div className="container">
<h1><div className="main-title">Welcome to WhyML Test App</div></h1>,
<p><div className="intro">This is a test application to verify WhyML CLI functionality works correctly.</div></p>,
<div><div className="features-section">
<h2><div className="section-title">Features</div></h2>,
<ul><div className="feature-list">
<li><div>CLI Commands</div></li>,
<li><div>Natural Language Conversion</div></li>,
<li><div>Application Generators</div></li>,
<li><div>Development Server</div></li>
</div></ul>
</div></div>
</div></div>
    );
  };

  export default WhymlTestApp;