<?php
/**
 * Generated by WhyML - BIELIK.AI
 * Description: Polski Model Językowy LLM
 * PHP Component Class
 */

<?php

namespace App\Components;

use InvalidArgumentException;
use RuntimeException;

/**
 * Polski Model Językowy LLM
 *
 * @version 1.0.0
 * @author WhyML Generator
 * @package App\Components
 */
class BIELIKAIComponent
{
    /**
     * Component data
     * @var array
     */
    private array $data = [];

    /**
     * Component styles
     * @var array
     */
    private array $styles = [
            'rect_element_0' => 'stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(255,255,255); fill-rule: nonzero; opacity: 1; visibility: hidden;',
            'path_element_2' => 'stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;',
            'path_element_5' => 'stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: evenodd; opacity: 1;',
            'path_element_12' => 'stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(255,255,255); fill-rule: nonzero; opacity: 1;',
            'path_element_15' => 'stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(255,255,255); fill-rule: evenodd; opacity: 1;',
            'wp_block_file__button' => 'background:#32373c; color:#fff; text-decoration:none;',
            'is_layout_flex' => 'flex-wrap: wrap; align-items: center;',
            'has_black_color' => 'color: var(--wp--preset--color--black) !important;',
            'has_cyan_bluish_gray_color' => 'color: var(--wp--preset--color--cyan-bluish-gray) !important;',
            'has_white_color' => 'color: var(--wp--preset--color--white) !important;',
            'has_pale_pink_color' => 'color: var(--wp--preset--color--pale-pink) !important;',
            'has_vivid_red_color' => 'color: var(--wp--preset--color--vivid-red) !important;',
            'has_luminous_vivid_orange_color' => 'color: var(--wp--preset--color--luminous-vivid-orange) !important;',
            'has_luminous_vivid_amber_color' => 'color: var(--wp--preset--color--luminous-vivid-amber) !important;',
            'has_light_green_cyan_color' => 'color: var(--wp--preset--color--light-green-cyan) !important;',
            'has_vivid_green_cyan_color' => 'color: var(--wp--preset--color--vivid-green-cyan) !important;',
            'has_pale_cyan_blue_color' => 'color: var(--wp--preset--color--pale-cyan-blue) !important;',
            'has_vivid_cyan_blue_color' => 'color: var(--wp--preset--color--vivid-cyan-blue) !important;',
            'has_vivid_purple_color' => 'color: var(--wp--preset--color--vivid-purple) !important;',
            'has_black_background_color' => 'background-color: var(--wp--preset--color--black) !important;',
            'has_cyan_bluish_gray_background_color' => 'background-color: var(--wp--preset--color--cyan-bluish-gray) !important;',
            'has_white_background_color' => 'background-color: var(--wp--preset--color--white) !important;',
            'has_pale_pink_background_color' => 'background-color: var(--wp--preset--color--pale-pink) !important;',
            'has_vivid_red_background_color' => 'background-color: var(--wp--preset--color--vivid-red) !important;',
            'has_luminous_vivid_orange_background_color' => 'background-color: var(--wp--preset--color--luminous-vivid-orange) !important;',
            'has_luminous_vivid_amber_background_color' => 'background-color: var(--wp--preset--color--luminous-vivid-amber) !important;',
            'has_light_green_cyan_background_color' => 'background-color: var(--wp--preset--color--light-green-cyan) !important;',
            'has_vivid_green_cyan_background_color' => 'background-color: var(--wp--preset--color--vivid-green-cyan) !important;',
            'has_pale_cyan_blue_background_color' => 'background-color: var(--wp--preset--color--pale-cyan-blue) !important;',
            'has_vivid_cyan_blue_background_color' => 'background-color: var(--wp--preset--color--vivid-cyan-blue) !important;',
            'has_vivid_purple_background_color' => 'background-color: var(--wp--preset--color--vivid-purple) !important;',
            'has_black_border_color' => 'border-color: var(--wp--preset--color--black) !important;',
            'has_cyan_bluish_gray_border_color' => 'border-color: var(--wp--preset--color--cyan-bluish-gray) !important;',
            'has_white_border_color' => 'border-color: var(--wp--preset--color--white) !important;',
            'has_pale_pink_border_color' => 'border-color: var(--wp--preset--color--pale-pink) !important;',
            'has_vivid_red_border_color' => 'border-color: var(--wp--preset--color--vivid-red) !important;',
            'has_luminous_vivid_orange_border_color' => 'border-color: var(--wp--preset--color--luminous-vivid-orange) !important;',
            'has_luminous_vivid_amber_border_color' => 'border-color: var(--wp--preset--color--luminous-vivid-amber) !important;',
            'has_light_green_cyan_border_color' => 'border-color: var(--wp--preset--color--light-green-cyan) !important;',
            'has_vivid_green_cyan_border_color' => 'border-color: var(--wp--preset--color--vivid-green-cyan) !important;',
            'has_pale_cyan_blue_border_color' => 'border-color: var(--wp--preset--color--pale-cyan-blue) !important;',
            'has_vivid_cyan_blue_border_color' => 'border-color: var(--wp--preset--color--vivid-cyan-blue) !important;',
            'has_vivid_purple_border_color' => 'border-color: var(--wp--preset--color--vivid-purple) !important;',
            'has_vivid_cyan_blue_to_vivid_purple_gradient_background' => 'background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;',
            'has_light_green_cyan_to_vivid_green_cyan_gradient_background' => 'background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;',
            'has_luminous_vivid_amber_to_luminous_vivid_orange_gradient_background' => 'background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;',
            'has_luminous_vivid_orange_to_vivid_red_gradient_background' => 'background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important;',
            'has_very_light_gray_to_cyan_bluish_gray_gradient_background' => 'background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important;',
            'has_cool_to_warm_spectrum_gradient_background' => 'background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important;',
            'has_blush_light_purple_gradient_background' => 'background: var(--wp--preset--gradient--blush-light-purple) !important;',
            'has_blush_bordeaux_gradient_background' => 'background: var(--wp--preset--gradient--blush-bordeaux) !important;',
            'has_luminous_dusk_gradient_background' => 'background: var(--wp--preset--gradient--luminous-dusk) !important;',
            'has_pale_ocean_gradient_background' => 'background: var(--wp--preset--gradient--pale-ocean) !important;',
            'has_electric_grass_gradient_background' => 'background: var(--wp--preset--gradient--electric-grass) !important;',
            'has_midnight_gradient_background' => 'background: var(--wp--preset--gradient--midnight) !important;',
            'has_small_font_size' => 'font-size: var(--wp--preset--font-size--small) !important;',
            'has_medium_font_size' => 'font-size: var(--wp--preset--font-size--medium) !important;',
            'has_large_font_size' => 'font-size: var(--wp--preset--font-size--large) !important;',
            'has_x_large_font_size' => 'font-size: var(--wp--preset--font-size--x-large) !important;',
            'page_content_a' => 'text-decoration: none;'
        ];

    /**
     * Constructor
     * @param array $data Initial component data
     */
    public function __construct(array $data = []): void
    {
        $this->data = $data;
    }

    /**
     * Render the component
     * @return string HTML output
     */
    public function render(): string
    {
        $html = '';

        $html .= '<main' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['id' => 'content', 'class' => 'site-main post-20 page type-page status-publish has-post-thumbnail hentry']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'page-content']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor elementor-20']) . '>';
        $html .= '<section' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-section elementor-top-section elementor-element elementor-element-6dcbf498 elementor-section-boxed elementor-section-height-default elementor-section-height-default elementor-invisible']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-container elementor-column-gap-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-79ab2731']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-4213d79d elementor-widget elementor-widget-image']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['href' => '/']) . '>';
        $html .= '<img' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['src' => 'https://bielik.ai/wp-content/uploads/2024/08/Bielik_Secondary_Rabarbar-300x82.webp', 'class' => 'attachment-medium size-medium wp-image-104']) . '></div>';
        $html .= '</img>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-36c43e7e']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap']) . '></div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</section>';
        $html .= '<section' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-section elementor-top-section elementor-element elementor-element-4c2a1112 elementor-reverse-tablet elementor-reverse-mobile elementor-section-boxed elementor-section-height-default elementor-section-height-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-container elementor-column-gap-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-66 elementor-top-column elementor-element elementor-element-2c42461f elementor-invisible']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-61446380 elementor-widget elementor-widget-jkit_heading']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'jeg-elementor-kit jkit-heading align- align-tablet-center align-mobile- jeg_module_20__68cfa66247475']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'heading-section-title display-inline-block']) . '>';
        $html .= '<h1' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'heading-title']) . '>' . $this->escapeHtml('BIELIK-11B-v2') . '</div>';
        $html .= '</h1>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-24eea98 elementor-widget__width-initial elementor-widget elementor-widget-jkit_heading']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'jeg-elementor-kit jkit-heading align- align-tablet-center align-mobile- jeg_module_20_1_68cfa662486ad']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'heading-section-title display-inline-block']) . '>';
        $html .= '<h1' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'heading-title']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'style-color']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . '' . '>' . $this->escapeHtml('Large Language Model') . '</div>';
        $html .= '</span>';
        $html .= '</div>';
        $html .= '</span>';
        $html .= '</div>';
        $html .= '</h1>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-760153c1 elementor-widget elementor-widget-text-editor']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-74b033eb elementor-widget elementor-widget-text-editor']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '></div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-6ed05fb3 elementor-tablet-align-center elementor-widget elementor-widget-button']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-button-wrapper']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-button elementor-button-link elementor-size-sm', 'href' => 'http://chat.bielik.ai']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-button-content-wrapper']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-button-text']) . '>' . $this->escapeHtml('Porozmawiaj z Bielikiem') . '</div>';
        $html .= '</span>';
        $html .= '</div>';
        $html .= '</span>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-62901256']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-456f8c23 elementor-widget__width-initial elementor-widget elementor-widget-image']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<img' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['src' => 'https://bielik.ai/wp-content/uploads/2024/08/image_orzel-768x597.png', 'class' => 'attachment-medium_large size-medium_large wp-image-287']) . '></div>';
        $html .= '</img>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</section>';
        $html .= '<section' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-section elementor-top-section elementor-element elementor-element-50ba09bf elementor-section-boxed elementor-section-height-default elementor-section-height-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-container elementor-column-gap-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-a535de9']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<section' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-section elementor-inner-section elementor-element elementor-element-8ec0b25 elementor-section-full_width elementor-section-height-default elementor-section-height-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-container elementor-column-gap-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-6a6f8687 elementor-invisible']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-e0fecbe elementor-widget elementor-widget-image']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<img' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['src' => 'https://bielik.ai/wp-content/uploads/2024/08/image_06-768x768.png', 'class' => 'attachment-medium_large size-medium_large wp-image-212']) . '></div>';
        $html .= '</img>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-66 elementor-inner-column elementor-element elementor-element-2320fe0b elementor-invisible']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-7a98438a elementor-widget elementor-widget-heading']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<h2' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-heading-title elementor-size-default']) . '>' . $this->escapeHtml('Efekt pracy społeczności entuzjastów sztucznej inteligencji') . '</div>';
        $html .= '</h2>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-20cb7e1f elementor-widget__width-initial elementor-widget elementor-widget-text-editor']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<p' . '' . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . '' . '></div>';
        $html .= '</div>';
        $html .= '</p>';
        $html .= '<p' . '' . '>';
        $html .= '<div' . '' . '>' . $this->escapeHtml('Bielik został opracowany na bazie modelu Mistral-7B, jednak znacząco go rozbudowaliśmy, czyniąc go jednym z najpotężniejszych modeli językowych stworzonych w Polsce.') . '</div>';
        $html .= '</p>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</section>';
        $html .= '<section' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-section elementor-inner-section elementor-element elementor-element-850b9b6 elementor-section-full_width elementor-section-height-default elementor-section-height-default elementor-invisible']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-container elementor-column-gap-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-2febf3c0']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap']) . '></div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-e6fcfde']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-241a8fc elementor-widget elementor-widget-jkit_fun_fact']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'jeg-elementor-kit jkit-fun-fact align-center hover-from-left elementor-animation- jeg_module_20_2_68cfa6624cb42']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'fun-fact-inner']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'content']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'number-wrapper']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'prefix']) . '></div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'number']) . '>' . $this->escapeHtml('0') . '</div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'suffix']) . '>' . $this->escapeHtml('mld') . '</div>';
        $html .= '</span>';
        $html .= '<div' . '' . '></div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<h3' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'title']) . '>' . $this->escapeHtml('Parametrów') . '</div>';
        $html .= '</h3>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-61f60fd rm-zero elementor-widget elementor-widget-jkit_fun_fact']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'jeg-elementor-kit jkit-fun-fact align-center hover-from-left elementor-animation- jeg_module_20_3_68cfa6624d43c']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'fun-fact-inner']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'content']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'number-wrapper']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'prefix']) . '></div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'number']) . '>' . $this->escapeHtml('0') . '</div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'suffix']) . '></div>';
        $html .= '</span>';
        $html .= '<div' . '' . '></div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<h3' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'title']) . '>' . $this->escapeHtml('Darmowy model') . '</div>';
        $html .= '</h3>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-7389f1b3']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-6eeeb40d elementor-widget elementor-widget-jkit_fun_fact']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'jeg-elementor-kit jkit-fun-fact align-center hover-from-left elementor-animation- jeg_module_20_4_68cfa6624dc80']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'fun-fact-inner']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'content']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'number-wrapper']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'prefix']) . '></div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'number']) . '>' . $this->escapeHtml('0') . '</div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'suffix']) . '></div>';
        $html .= '</span>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<h3' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'title']) . '>' . $this->escapeHtml('w rankingu Areny') . '</div>';
        $html .= '</h3>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-bcceff1 elementor-widget elementor-widget-jkit_fun_fact']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'jeg-elementor-kit jkit-fun-fact align-center hover-from-left elementor-animation- jeg_module_20_5_68cfa6624e4bc']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'fun-fact-inner']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'content']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'number-wrapper']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'prefix']) . '></div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'number']) . '>' . $this->escapeHtml('0') . '</div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'suffix']) . '>' . $this->escapeHtml('tys') . '</div>';
        $html .= '</span>';
        $html .= '<div' . '' . '></div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<h3' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'title']) . '>' . $this->escapeHtml('Kontekst') . '</div>';
        $html .= '</h3>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-b9d3591']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-a13a36a link-container e-flex e-con-boxed e-con e-parent', 'href' => 'https://huggingface.co/speakleash']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'e-con-inner']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-813e5c7 without-number elementor-widget elementor-widget-jkit_fun_fact']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'jeg-elementor-kit jkit-fun-fact align-center hover-from-left elementor-animation- jeg_module_20_6_68cfa6624eccd']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'fun-fact-inner']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'icon elementor-animation-']) . '>';
        $html .= '<div' . '' . '></div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'content']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'number-wrapper']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'prefix']) . '></div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'number']) . '>' . $this->escapeHtml('0') . '</div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'suffix']) . '></div>';
        $html .= '</span>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<h2' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'title']) . '>' . $this->escapeHtml('Dostępny na Hugging Face') . '</div>';
        $html .= '</h2>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-89aacc0 link-container e-flex e-con-boxed e-con e-parent', 'href' => 'https://arena.speakleash.org.pl/']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'e-con-inner']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-55e79f7 without-number elementor-widget elementor-widget-jkit_fun_fact']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'jeg-elementor-kit jkit-fun-fact align-center hover-from-left elementor-animation- jeg_module_20_7_68cfa6624ff9d']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'fun-fact-inner']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'icon elementor-animation-']) . '>';
        $html .= '<img' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['src' => 'https://bielik.ai/wp-content/uploads/2024/08/rsz_1swords256x256_1.png', 'class' => 'attachment-thumbnail size-thumbnail']) . '></div>';
        $html .= '</img>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'content']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'number-wrapper']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'prefix']) . '></div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'number']) . '>' . $this->escapeHtml('0') . '</div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'suffix']) . '></div>';
        $html .= '</span>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<h2' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'title']) . '>' . $this->escapeHtml('Chat Arena Porównaj modele') . '</div>';
        $html .= '</h2>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</section>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</section>';
        $html .= '<section' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-section elementor-top-section elementor-element elementor-element-77176f31 elementor-section-boxed elementor-section-height-default elementor-section-height-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-container elementor-column-gap-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-74297053']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<section' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-section elementor-inner-section elementor-element elementor-element-1b6fef6c elementor-section-full_width elementor-hidden-desktop elementor-hidden-tablet elementor-hidden-mobile elementor-section-height-default elementor-section-height-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-container elementor-column-gap-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-5069c10a elementor-invisible']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-663a5955 jkit-equal-height-enable elementor-hidden-desktop elementor-hidden-tablet elementor-hidden-mobile elementor-widget elementor-widget-jkit_image_box']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'jeg-elementor-kit jkit-image-box style-default elementor-animation- jeg_module_20_8_68cfa6625317e']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'image-box-header elementor-animation-']) . '></div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'image-box-body']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'body-inner']) . '>';
        $html .= '<h3' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'body-title icon-position-before']) . '>' . $this->escapeHtml('Bezpieczeństwo i prywatnosć') . '</div>';
        $html .= '</h3>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'body-description']) . '>';
        $html .= '<p' . '' . '>';
        $html .= '<div' . '' . '>' . $this->escapeHtml('Nasze projekty opierają się na zasadach open-source i open-science, co pozwala na transparentność oraz szeroką współpracę z globalną społecznością badawczą i technologiczną​​.') . '</div>';
        $html .= '</p>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'body-button']) . '></div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-235049a0 elementor-widget__width-auto elementor-widget elementor-widget-image']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<img' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['src' => 'https://bielik.ai/wp-content/uploads/2024/08/Group-27.png', 'class' => 'attachment-full size-full wp-image-27']) . '></div>';
        $html .= '</img>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-64dd2c8f elementor-invisible']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-65328c75 jkit-equal-height-enable elementor-widget__width-initial elementor-hidden-desktop elementor-hidden-tablet elementor-hidden-mobile elementor-widget elementor-widget-jkit_image_box']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'jeg-elementor-kit jkit-image-box style-default elementor-animation- jeg_module_20_9_68cfa66253b3c']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'image-box-header elementor-animation-']) . '></div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'image-box-body']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'body-inner']) . '>';
        $html .= '<h3' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'body-title icon-position-before']) . '>' . $this->escapeHtml('Koszty i skalowalność') . '</div>';
        $html .= '</h3>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'body-description']) . '>';
        $html .= '<p' . '' . '>';
        $html .= '<div' . '' . '>' . $this->escapeHtml('Lokalny LLM może być tańszy do wdrożenia i utrzymania niż korzystanie z usług takich jak OpenAI. Ponadto, opłacalność stosowania lokalnego modelu rośnie ze skalą jego wykorzystania, co jest kluczowe dla firm przetwarzających duże ilości danych lub obsługujących liczne zapytania.') . '</div>';
        $html .= '</p>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'body-button']) . '></div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-49b8ed59 elementor-widget__width-auto elementor-hidden-desktop elementor-hidden-tablet elementor-hidden-mobile elementor-widget elementor-widget-image']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<img' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['src' => 'https://bielik.ai/wp-content/uploads/2024/08/Group-30.png', 'class' => 'attachment-full size-full wp-image-28']) . '></div>';
        $html .= '</img>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-aee072d elementor-invisible']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-6c33ef7 jkit-equal-height-enable elementor-hidden-desktop elementor-hidden-tablet elementor-hidden-mobile elementor-widget elementor-widget-jkit_image_box']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'jeg-elementor-kit jkit-image-box style-default elementor-animation- jeg_module_20_10_68cfa662548bc']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'image-box-header elementor-animation-']) . '></div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'image-box-body']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'body-inner']) . '>';
        $html .= '<h3' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'body-title icon-position-before']) . '>' . $this->escapeHtml('Ekosystem i Społeczność') . '</div>';
        $html .= '</h3>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'body-description']) . '>';
        $html .= '<p' . '' . '>';
        $html .= '<div' . '' . '>' . $this->escapeHtml('Wzmacnianie i rozwój polskiego ekosystemu sztucznej inteligencji oraz dbanie o aktywną i zaangażowaną społeczność.') . '</div>';
        $html .= '</p>';
        $html .= '<p' . '' . '>';
        $html .= '<div' . '' . '>' . $this->escapeHtml('Wspieramy rozwój umiejętności wśród programistów, badaczy i entuzjastów AI poprzez otwartą wymianę wiedzy oraz narzędzi') . '</div>';
        $html .= '</p>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'body-button']) . '></div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-38f1d65a elementor-widget__width-auto elementor-widget elementor-widget-image']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<img' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['src' => 'https://bielik.ai/wp-content/uploads/2024/08/Group-23.png', 'class' => 'attachment-full size-full wp-image-29']) . '></div>';
        $html .= '</img>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</section>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</section>';
        $html .= '<section' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-section elementor-top-section elementor-element elementor-element-6c22b27a elementor-section-boxed elementor-section-height-default elementor-section-height-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-container elementor-column-gap-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-10fcde95']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<section' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-section elementor-inner-section elementor-element elementor-element-7ebff4f6 elementor-section-full_width elementor-section-height-default elementor-section-height-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-container elementor-column-gap-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-7fc0fb39']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-651abbb4 jkit-equal-height-disable elementor-invisible elementor-widget elementor-widget-jkit_icon_box']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'jeg-elementor-kit jkit-icon-box icon-position-left elementor-animation- jeg_module_20_11_68cfa66259642']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['href' => 'mailto:biuro@speakleash.org.pl', 'class' => 'icon-box-link']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'jkit-icon-box-wrapper hover-from-left']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'icon-box icon-box-header elementor-animation-']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'icon style-color']) . '>';
        $html .= '<div' . '' . '></div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'icon-box icon-box-body']) . '>';
        $html .= '<h2' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'title']) . '>' . $this->escapeHtml('Email') . '</div>';
        $html .= '</h2>';
        $html .= '<p' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'icon-box-description']) . '>' . $this->escapeHtml('biuro@speakleash.org.pl') . '</div>';
        $html .= '</p>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-239cae2c']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-7bcbd3b0 elementor-shape-circle e-grid-align-right elementor-grid-tablet-2 e-grid-align-mobile-center elementor-grid-mobile-1 elementor-grid-0 elementor-widget elementor-widget-social-icons']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-social-icons-wrapper elementor-grid']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-grid-item']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-icon elementor-social-icon elementor-social-icon-jki-discord elementor-repeater-item-a5e322d', 'href' => 'https://discord.com/invite/ZJwCMrxwT7']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-screen-only']) . '>' . $this->escapeHtml('Jki-discord') . '</div>';
        $html .= '</span>';
        $html .= '<div' . '' . '></div>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-grid-item']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-icon elementor-social-icon elementor-social-icon-linkedin elementor-repeater-item-1bb6345', 'href' => 'https://www.linkedin.com/company/speakleash/']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-screen-only']) . '>' . $this->escapeHtml('Linkedin') . '</div>';
        $html .= '</span>';
        $html .= '<div' . '' . '></div>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-grid-item']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-icon elementor-social-icon elementor-social-icon-github elementor-repeater-item-47e5f5e', 'href' => 'https://github.com/speakleash']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-screen-only']) . '>' . $this->escapeHtml('Github') . '</div>';
        $html .= '</span>';
        $html .= '<div' . '' . '></div>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-grid-item']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-icon elementor-social-icon elementor-social-icon-x-twitter elementor-repeater-item-abbbcbb', 'href' => 'https://x.com/Speak_Leash']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-screen-only']) . '>' . $this->escapeHtml('X-twitter') . '</div>';
        $html .= '</span>';
        $html .= '<div' . '' . '></div>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-grid-item']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-icon elementor-social-icon elementor-social-icon-facebook elementor-repeater-item-e76b3c6', 'href' => 'https://www.facebook.com/Speakleash/']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-screen-only']) . '>' . $this->escapeHtml('Facebook') . '</div>';
        $html .= '</span>';
        $html .= '<div' . '' . '></div>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-grid-item']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-icon elementor-social-icon elementor-social-icon- elementor-repeater-item-9f2ad43', 'href' => 'https://huggingface.co/speakleash']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-screen-only']) . '></div>';
        $html .= '</span>';
        $html .= '<div' . '' . '></div>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</span>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-grid-item']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-icon elementor-social-icon elementor-social-icon-envelope elementor-repeater-item-0f366f0', 'href' => 'mailto:team@speakleash.org']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-screen-only']) . '>' . $this->escapeHtml('Envelope') . '</div>';
        $html .= '</span>';
        $html .= '<div' . '' . '></div>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</span>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</section>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-5f087443 elementor-widget-divider--view-line elementor-widget elementor-widget-divider']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-divider']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-divider-separator']) . '></div>';
        $html .= '</span>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<section' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-section elementor-inner-section elementor-element elementor-element-80b265d elementor-section-full_width elementor-reverse-mobile elementor-section-height-default elementor-section-height-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-container elementor-column-gap-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-a407af0']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-1211840a elementor-widget elementor-widget-text-editor']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<p' . '' . '>';
        $html .= '<div' . '' . '>' . $this->escapeHtml('©
2025 Bielik.ai | Wszelkie prawa zastrzeżone') . '</div>';
        $html .= '</p>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-1c4b2b1']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-257189f elementor-widget__width-initial elementor-widget elementor-widget-image']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['href' => 'https://www.cyfronet.pl/']) . '>';
        $html .= '<img' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['src' => 'https://bielik.ai/wp-content/uploads/2024/08/CYFRONET_1-1024x488.png', 'class' => 'attachment-large size-large wp-image-208']) . '></div>';
        $html .= '</img>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-369b5234 elementor-widget__width-initial elementor-widget elementor-widget-image']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['href' => 'https://speakleash.org/']) . '>';
        $html .= '<img' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['src' => 'https://bielik.ai/wp-content/uploads/2024/08/speakleash_logo_2-Copy-modified.png', 'class' => 'attachment-full size-full wp-image-207']) . '></div>';
        $html .= '</img>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-29392716']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-e468630 elementor-icon-list--layout-inline elementor-align-right elementor-mobile-align-center elementor-tablet-align-right elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<ul' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-icon-list-items elementor-inline-items']) . '>';
        $html .= '<li' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-icon-list-item elementor-inline-item']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['href' => '/terms']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-icon-list-text']) . '>' . $this->escapeHtml('Warunki użytkowania modelu') . '</div>';
        $html .= '</span>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</li>';
        $html .= '<li' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-icon-list-item elementor-inline-item']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['href' => '/polityka-prywatnosci']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-icon-list-text']) . '>' . $this->escapeHtml('Polityka Prywatności') . '</div>';
        $html .= '</span>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</li>';
        $html .= '</div>';
        $html .= '</ul>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</section>';
        $html .= '<section' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-section elementor-inner-section elementor-element elementor-element-bbf1163 elementor-section-full_width elementor-reverse-mobile elementor-section-height-default elementor-section-height-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-container elementor-column-gap-default']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-column elementor-col-100 elementor-inner-column elementor-element elementor-element-fc8469d']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-wrap elementor-element-populated']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-e28a1a3 elementor-widget-divider--view-line elementor-widget elementor-widget-divider']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-divider']) . '>';
        $html .= '<span' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-divider-separator']) . '></div>';
        $html .= '</span>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-8fb2f0e elementor-widget elementor-widget-heading']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<h2' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-heading-title elementor-size-default']) . '>' . $this->escapeHtml('Partnerzy i sponsorzy') . '</div>';
        $html .= '</h2>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-element elementor-element-50c4959 elementor-widget elementor-widget-shortcode']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-widget-container']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'elementor-shortcode']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'rt-container-fluid rt-wpls', 'id' => 'rt-container-1280752518']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'rt-row grid-layout']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'rt-col-md-3 rt-col-sm-6 rt-col-xs-12']) . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['class' => 'single-logo-container']) . '>';
        $html .= '<a' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['href' => 'https://deviniti.com']) . '>';
        $html .= '<img' . '' . '>';
        $html .= '<div' . $this->buildAttributes(['src' => 'https://bielik.ai/wp-content/uploads/2025/01/deviniti-logo-footer.svg', 'class' => 'wls-logo', 'alt' => 'DEVINITI', 'title' => 'Deviniti']) . '></div>';
        $html .= '</img>';
        $html .= '</div>';
        $html .= '</a>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</section>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</section>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</main>';

        return $html;
    }

    /**
     * Get component styles as CSS
     * @return string CSS styles
     */
    public function getStyles(): string
    {
        $css = '';

        $css .= '.rect_element_0 { stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(255,255,255); fill-rule: nonzero; opacity: 1; visibility: hidden; }' . "\n";
        $css .= '.path_element_2 { stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1; }' . "\n";
        $css .= '.path_element_5 { stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: evenodd; opacity: 1; }' . "\n";
        $css .= '.path_element_12 { stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(255,255,255); fill-rule: nonzero; opacity: 1; }' . "\n";
        $css .= '.path_element_15 { stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(255,255,255); fill-rule: evenodd; opacity: 1; }' . "\n";
        $css .= '.wp_block_file__button { background:#32373c; color:#fff; text-decoration:none; }' . "\n";
        $css .= '.is_layout_flex { flex-wrap: wrap; align-items: center; }' . "\n";
        $css .= '.has_black_color { color: var(--wp--preset--color--black) !important; }' . "\n";
        $css .= '.has_cyan_bluish_gray_color { color: var(--wp--preset--color--cyan-bluish-gray) !important; }' . "\n";
        $css .= '.has_white_color { color: var(--wp--preset--color--white) !important; }' . "\n";
        $css .= '.has_pale_pink_color { color: var(--wp--preset--color--pale-pink) !important; }' . "\n";
        $css .= '.has_vivid_red_color { color: var(--wp--preset--color--vivid-red) !important; }' . "\n";
        $css .= '.has_luminous_vivid_orange_color { color: var(--wp--preset--color--luminous-vivid-orange) !important; }' . "\n";
        $css .= '.has_luminous_vivid_amber_color { color: var(--wp--preset--color--luminous-vivid-amber) !important; }' . "\n";
        $css .= '.has_light_green_cyan_color { color: var(--wp--preset--color--light-green-cyan) !important; }' . "\n";
        $css .= '.has_vivid_green_cyan_color { color: var(--wp--preset--color--vivid-green-cyan) !important; }' . "\n";
        $css .= '.has_pale_cyan_blue_color { color: var(--wp--preset--color--pale-cyan-blue) !important; }' . "\n";
        $css .= '.has_vivid_cyan_blue_color { color: var(--wp--preset--color--vivid-cyan-blue) !important; }' . "\n";
        $css .= '.has_vivid_purple_color { color: var(--wp--preset--color--vivid-purple) !important; }' . "\n";
        $css .= '.has_black_background_color { background-color: var(--wp--preset--color--black) !important; }' . "\n";
        $css .= '.has_cyan_bluish_gray_background_color { background-color: var(--wp--preset--color--cyan-bluish-gray) !important; }' . "\n";
        $css .= '.has_white_background_color { background-color: var(--wp--preset--color--white) !important; }' . "\n";
        $css .= '.has_pale_pink_background_color { background-color: var(--wp--preset--color--pale-pink) !important; }' . "\n";
        $css .= '.has_vivid_red_background_color { background-color: var(--wp--preset--color--vivid-red) !important; }' . "\n";
        $css .= '.has_luminous_vivid_orange_background_color { background-color: var(--wp--preset--color--luminous-vivid-orange) !important; }' . "\n";
        $css .= '.has_luminous_vivid_amber_background_color { background-color: var(--wp--preset--color--luminous-vivid-amber) !important; }' . "\n";
        $css .= '.has_light_green_cyan_background_color { background-color: var(--wp--preset--color--light-green-cyan) !important; }' . "\n";
        $css .= '.has_vivid_green_cyan_background_color { background-color: var(--wp--preset--color--vivid-green-cyan) !important; }' . "\n";
        $css .= '.has_pale_cyan_blue_background_color { background-color: var(--wp--preset--color--pale-cyan-blue) !important; }' . "\n";
        $css .= '.has_vivid_cyan_blue_background_color { background-color: var(--wp--preset--color--vivid-cyan-blue) !important; }' . "\n";
        $css .= '.has_vivid_purple_background_color { background-color: var(--wp--preset--color--vivid-purple) !important; }' . "\n";
        $css .= '.has_black_border_color { border-color: var(--wp--preset--color--black) !important; }' . "\n";
        $css .= '.has_cyan_bluish_gray_border_color { border-color: var(--wp--preset--color--cyan-bluish-gray) !important; }' . "\n";
        $css .= '.has_white_border_color { border-color: var(--wp--preset--color--white) !important; }' . "\n";
        $css .= '.has_pale_pink_border_color { border-color: var(--wp--preset--color--pale-pink) !important; }' . "\n";
        $css .= '.has_vivid_red_border_color { border-color: var(--wp--preset--color--vivid-red) !important; }' . "\n";
        $css .= '.has_luminous_vivid_orange_border_color { border-color: var(--wp--preset--color--luminous-vivid-orange) !important; }' . "\n";
        $css .= '.has_luminous_vivid_amber_border_color { border-color: var(--wp--preset--color--luminous-vivid-amber) !important; }' . "\n";
        $css .= '.has_light_green_cyan_border_color { border-color: var(--wp--preset--color--light-green-cyan) !important; }' . "\n";
        $css .= '.has_vivid_green_cyan_border_color { border-color: var(--wp--preset--color--vivid-green-cyan) !important; }' . "\n";
        $css .= '.has_pale_cyan_blue_border_color { border-color: var(--wp--preset--color--pale-cyan-blue) !important; }' . "\n";
        $css .= '.has_vivid_cyan_blue_border_color { border-color: var(--wp--preset--color--vivid-cyan-blue) !important; }' . "\n";
        $css .= '.has_vivid_purple_border_color { border-color: var(--wp--preset--color--vivid-purple) !important; }' . "\n";
        $css .= '.has_vivid_cyan_blue_to_vivid_purple_gradient_background { background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important; }' . "\n";
        $css .= '.has_light_green_cyan_to_vivid_green_cyan_gradient_background { background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important; }' . "\n";
        $css .= '.has_luminous_vivid_amber_to_luminous_vivid_orange_gradient_background { background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important; }' . "\n";
        $css .= '.has_luminous_vivid_orange_to_vivid_red_gradient_background { background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important; }' . "\n";
        $css .= '.has_very_light_gray_to_cyan_bluish_gray_gradient_background { background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important; }' . "\n";
        $css .= '.has_cool_to_warm_spectrum_gradient_background { background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important; }' . "\n";
        $css .= '.has_blush_light_purple_gradient_background { background: var(--wp--preset--gradient--blush-light-purple) !important; }' . "\n";
        $css .= '.has_blush_bordeaux_gradient_background { background: var(--wp--preset--gradient--blush-bordeaux) !important; }' . "\n";
        $css .= '.has_luminous_dusk_gradient_background { background: var(--wp--preset--gradient--luminous-dusk) !important; }' . "\n";
        $css .= '.has_pale_ocean_gradient_background { background: var(--wp--preset--gradient--pale-ocean) !important; }' . "\n";
        $css .= '.has_electric_grass_gradient_background { background: var(--wp--preset--gradient--electric-grass) !important; }' . "\n";
        $css .= '.has_midnight_gradient_background { background: var(--wp--preset--gradient--midnight) !important; }' . "\n";
        $css .= '.has_small_font_size { font-size: var(--wp--preset--font-size--small) !important; }' . "\n";
        $css .= '.has_medium_font_size { font-size: var(--wp--preset--font-size--medium) !important; }' . "\n";
        $css .= '.has_large_font_size { font-size: var(--wp--preset--font-size--large) !important; }' . "\n";
        $css .= '.has_x_large_font_size { font-size: var(--wp--preset--font-size--x-large) !important; }' . "\n";
        $css .= '.page_content_a { text-decoration: none; }' . "\n";

        return $css;
    }

    /**
     * Set component data
     * @param string $key Data key
     * @param mixed $value Data value
     * @return self
     */
    public function setData(string $key, mixed $value): self
    {
        $this->data[$key] = $value;
        return $this;
    }

    /**
     * Get component data
     * @param string $key Data key
     * @param mixed $default Default value
     * @return mixed
     */
    public function getData(string $key, mixed $default = null): mixed
    {
        return $this->data[$key] ?? $default;
    }


    /**
     * Escape HTML content
     * @param string $content Content to escape
     * @return string Escaped content
     */
    private function escapeHtml(string $content): string
    {
        return htmlspecialchars($content, ENT_QUOTES | ENT_HTML5, 'UTF-8');
    }

    /**
     * Build HTML attributes string
     * @param array $attributes Attributes array
     * @return string Attributes string
     */
    private function buildAttributes(array $attributes): string
    {
        $attr = [];
        foreach ($attributes as $key => $value) {
            if ($value !== null && $value !== false) {
                $attr[] = $key . '="' . $this->escapeHtml($value) . '"';
            }
        }
        return empty($attr) ? '' : ' ' . implode(' ', $attr);
    }
}