version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./output:/var/www/html
      - ./src:/var/www/html/src
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped