/**
 * Generated by WhyML - Tom Sapletta ' Embedded System Software & Hardware Developer, Germany Essen
 * Description: Hardware and Software Development by Tom Sapletta. I share here my ideas, tests, solutions and opinions. I am develop software in PHP7, Python, NodeJS, JavaScript, Java on Windows, Linux, Android. I am inventor of products in embedded systems as IoT and smart products.
 * React Component
 */

import React from 'react';
import styles from './styles.module.css';

interface Props {
  className?: string;
  style?: React.CSSProperties;
}

const TomSaplettaEmbeddedSystemSoftwareHardwareDeveloperGermanyEssen: React.FC<Props> = (props) => {
    return (
      <article><div id="post-4038" className="col-sm-12 col-md-6 col-lg-4 col-xl-3 wpb_column home post-4038 post type-post status-publish format-standard has-post-thumbnail hentry category-kariera tag-debugowanie tag-frustracja tag-kariera tag-programowanie"><a><div href="https://tom.sapletta.pl/kariera/%f0%9f%a4%94-jak-radzicie-sobie-z-frustracja-w-pracy-developera/">
<img><div src="https://tom.sapletta.pl/wp-content/uploads/2024/11/Screenshot-from-2024-11-24-13-52-03-960x964.png" style={'zIndex': '11', 'width': '220px', 'position': 'absolute', 'top': '0', 'right': '0px', 'border': '1px solid #444'} /></img>,
<div><div className="post imagebg standard-height scrim" style={'backgroundImage': 'url(https://tom.sapletta.pl/wp-content/uploads/2024/11/Screenshot-from-2024-11-24-13-52-03-960x964.png)'}><div><div className="stick-to-bottom">
<h5><div className="type--uppercase"><a><div href="https://tom.sapletta.pl/category/kariera/">Kariera</div></a></div></h5>,
<h3><div><a><div href="https://tom.sapletta.pl/kariera/%f0%9f%a4%94-jak-radzicie-sobie-z-frustracja-w-pracy-developera/">🤔 Jak radzicie sobie z frustracją w pracy developera?</div></a></div></h3>,
<p><div>Po 2 dekadach latach w branży IT zauważyłem, że to temat, o którym mówimy za mało.</div></p>,
<a><div href="https://tom.sapletta.pl/kariera/%f0%9f%a4%94-jak-radzicie-sobie-z-frustracja-w-pracy-developera/">Continue Reading   →</div></a>
</div></div></div></div>
</div></a></div></article>
    );
  };

  export default TomSaplettaEmbeddedSystemSoftwareHardwareDeveloperGermanyEssen;