/**
 * Generated by WhyML - BIELIK.AI
 * Description: Polski Model Językowy LLM
 * React Component
 */

import React from 'react';
// External script: https://bielik.ai/wp-includes/js/jquery/jquery.min.js?ver=3.7.1
// External script: https://bielik.ai/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.4.1
// External script: https://www.googletagmanager.com/gtag/js?id=GT-M3K6SCT4
// External script: https://www.googletagmanager.com/gtag/js?id=G-YM3958RN9T
// External script: https://bielik.ai/wp-content/plugins/elementor/assets/js/webpack.runtime.min.js?ver=3.32.2
// External script: https://bielik.ai/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.32.2
// External script: https://bielik.ai/wp-includes/js/jquery/ui/core.min.js?ver=1.13.3
// External script: https://bielik.ai/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.32.2
// External script: https://bielik.ai/wp-content/plugins/metform/public/assets/lib/cute-alert/cute-alert.js?ver=4.0.6
// External script: https://bielik.ai/wp-content/plugins/jeg-elementor-kit/assets/js/elements/fun-fact.js?ver=2.6.14
// External script: https://bielik.ai/wp-content/plugins/jeg-elementor-kit/assets/js/elements/sticky-element.js?ver=2.6.14
// External script: https://bielik.ai/wp-content/plugins/elementor/assets/lib/font-awesome/js/v4-shims.min.js?ver=3.32.2
// External script: https://bielik.ai/wp-content/plugins/wp-logo-showcase/assets/vendor/jquery.actual.min.js?ver=1.5.0
// External script: https://bielik.ai/wp-content/plugins/wp-logo-showcase/assets/js/wplogoshowcase.js?ver=1.5.0
import styles from './styles.module.css';

interface Props {
  className?: string;
  style?: React.CSSProperties;
}

const BIELIKAI: React.FC<Props> = (props) => {
    return (
      <div type="container" className="page-container">
<div type="heading">BIELIK-11B-v2</div>,
<div type="heading">Large Language Model</div>,
<div type="heading">Efekt pracy społeczności entuzjastów sztucznej inteligencji</div>,
<div type="heading">Dostępny na Hugging Face</div>,
<div type="heading">Chat Arena Porównaj modele</div>,
<div type="heading">Email</div>,
<div type="heading">Partnerzy i sponsorzy</div>,
<div type="heading">Parametrów</div>,
<div type="heading">Darmowy model</div>,
<div type="heading">w rankingu Areny</div>,
<div type="heading">Kontekst</div>,
<div type="heading">Bezpieczeństwo i prywatnosć</div>,
<div type="heading">Koszty i skalowalność</div>,
<div type="heading">Ekosystem i Społeczność</div>,
<div type="paragraph">Bezpieczne przetwarzaniePełna kontrolaKompaktowa moc</div>,
<div type="paragraph">Bielik v2 opiera się na architekturze transformera, będąc modelem typu „decoder-only”, co oznacza, że do przetwarzania danych wejściowych wykorzystuje wyłącznie bloki dekodera.</div>,
<div type="paragraph">Bielik został opracowany na bazie modelu Mistral-7B, jednak znacząco go rozbudowaliśmy, czyniąc go jednym z najpotężniejszych modeli językowych stworzonych w Polsce.</div>,
<div type="paragraph">0 Dostępny na Hugging Face 0 Chat Arena Porównaj modele Bezpieczeństwo i prywatnosć Nasze projekty opierają się na zasadach open-source i open-science, co pozwala na transparentność oraz szeroką współpracę z globalną społecznością badawczą i technologiczną​​.</div>,
<div type="paragraph">Lokalny LLM może być tańszy do wdrożenia i utrzymania niż korzystanie z usług takich jak OpenAI. Ponadto, opłacalność stosowania lokalnego modelu rośnie ze skalą jego wykorzystania, co jest kluczowe dla firm przetwarzających duże ilości danych lub obsługujących liczne zapytania.</div>,
<div type="paragraph">Wzmacnianie i rozwój polskiego ekosystemu sztucznej inteligencji oraz dbanie o aktywną i zaangażowaną społeczność.</div>,
<div type="paragraph">Wspieramy rozwój umiejętności wśród programistów, badaczy i entuzjastów AI poprzez otwartą wymianę wiedzy oraz narzędzi</div>,
<div type="paragraph">biuro@speakleash.org.pl</div>,
<div type="paragraph">Github X-twitter Facebook Created with Fabric.js 5.2.4 Envelope © 2025 Bielik.ai | Wszelkie prawa zastrzeżone</div>,
<div type="image" src="https://bielik.ai/wp-content/uploads/2024/08/Bielik_Secondary_Rabarbar-300x82.webp" alt="" />,
<div type="image" src="https://bielik.ai/wp-content/uploads/2024/08/image_orzel-768x597.png" alt="" />,
<div type="image" src="https://bielik.ai/wp-content/uploads/2024/08/image_06-768x768.png" alt="" />,
<div type="image" src="https://bielik.ai/wp-content/uploads/2024/08/rsz_1swords256x256_1.png" alt="" />,
<div type="image" src="https://bielik.ai/wp-content/uploads/2024/08/Group-27.png" alt="" />,
<div type="image" src="https://bielik.ai/wp-content/uploads/2024/08/Group-30.png" alt="" />,
<div type="image" src="https://bielik.ai/wp-content/uploads/2024/08/Group-23.png" alt="" />,
<div type="image" src="https://bielik.ai/wp-content/uploads/2024/08/CYFRONET_1-1024x488.png" alt="" />,
<div type="image" src="https://bielik.ai/wp-content/uploads/2024/08/speakleash_logo_2-Copy-modified.png" alt="" />,
<div type="image" src="https://bielik.ai/wp-content/uploads/2025/01/deviniti-logo-footer.svg" alt="" />,
<div type="link" href="https://bielik.ai/#content">Przejdź do treści</div>,
<div type="link" href="https://bielik.ai/"></div>,
<div type="link" href="http://chat.bielik.ai">Porozmawiaj z Bielikiem</div>,
<div type="link" href="https://huggingface.co/speakleash">Created with Fabric.js 5.2.4 0 Dostępny na Hugging Face</div>,
<div type="link" href="https://arena.speakleash.org.pl/">0 Chat Arena Porównaj modele</div>,
<div type="link" href="mailto:biuro@speakleash.org.pl">Emailbiuro@speakleash.org.pl</div>,
<div type="link" href="https://discord.com/invite/ZJwCMrxwT7">Jki-discord</div>,
<div type="link" href="https://www.linkedin.com/company/speakleash/">Linkedin</div>,
<div type="link" href="https://github.com/speakleash">Github</div>,
<div type="link" href="https://x.com/Speak_Leash">X-twitter</div>,
<div type="link" href="https://www.facebook.com/Speakleash/">Facebook</div>,
<div type="link" href="https://huggingface.co/speakleash">Created with Fabric.js 5.2.4</div>,
<div type="link" href="mailto:team@speakleash.org">Envelope</div>,
<div type="link" href="https://www.cyfronet.pl/"></div>,
<div type="link" href="https://speakleash.org/"></div>,
<div type="link" href="https://bielik.ai/terms">Warunki użytkowania modelu</div>,
<div type="link" href="https://bielik.ai/polityka-prywatnosci">Polityka Prywatności</div>,
<div type="link" href="https://deviniti.com"></div>
</div>
    );
  };

  export default BIELIKAI;