/**
 * Generated by WhyML - Example Domain
 * Description: Content from Example Domain - scraped from example.com
 * React Component
 */

import React from 'react';
import styles from './styles.module.css';

interface Props {
  className?: string;
  style?: React.CSSProperties;
}

const ExampleDomain: React.FC<Props> = (props) => {
    return (
      <div />
    );
  };

  export default ExampleDomain;