<!--
  Generated by WhyML - Example Domain
  Description: Content from Example Domain - scraped from example.com
-->

<template>
  <div></div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'ExampleDomain',
  setup() {
    return {};
  }
});
</script>