<!--
  Generated by WhyML - BIELIK.AI
  Description: Polski Model Językowy LLM
-->

<template>
  <main id="content" class="site-main post-20 page type-page status-publish has-post-thumbnail hentry">
    <div class="page-content">
      <div class="elementor elementor-20">
        <section class="elementor-section elementor-top-section elementor-element elementor-element-6dcbf498 elementor-section-boxed elementor-section-height-default elementor-section-height-default elementor-invisible">
          <div class="elementor-container elementor-column-gap-default">
            <div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-79ab2731">
              <div class="elementor-widget-wrap elementor-element-populated">
                <div class="elementor-element elementor-element-4213d79d elementor-widget elementor-widget-image">
                  <div class="elementor-widget-container">
                    <a href="/">
                      <img src="https://bielik.ai/wp-content/uploads/2024/08/Bielik_Secondary_Rabarbar-300x82.webp" class="attachment-medium size-medium wp-image-104"></img>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-36c43e7e">
              <div class="elementor-widget-wrap"></div>
            </div>
          </div>
        </section>
        <section class="elementor-section elementor-top-section elementor-element elementor-element-4c2a1112 elementor-reverse-tablet elementor-reverse-mobile elementor-section-boxed elementor-section-height-default elementor-section-height-default">
          <div class="elementor-container elementor-column-gap-default">
            <div class="elementor-column elementor-col-66 elementor-top-column elementor-element elementor-element-2c42461f elementor-invisible">
              <div class="elementor-widget-wrap elementor-element-populated">
                <div class="elementor-element elementor-element-61446380 elementor-widget elementor-widget-jkit_heading">
                  <div class="elementor-widget-container">
                    <div class="jeg-elementor-kit jkit-heading align- align-tablet-center align-mobile- jeg_module_20__68cfa66247475">
                      <div class="heading-section-title display-inline-block">
                        <h1 class="heading-title">BIELIK-11B-v2</h1>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="elementor-element elementor-element-24eea98 elementor-widget__width-initial elementor-widget elementor-widget-jkit_heading">
                  <div class="elementor-widget-container">
                    <div class="jeg-elementor-kit jkit-heading align- align-tablet-center align-mobile- jeg_module_20_1_68cfa662486ad">
                      <div class="heading-section-title display-inline-block">
                        <h1 class="heading-title">
                          <span class="style-color">
                            <span>Large Language Model</span>
                          </span>
                        </h1>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="elementor-element elementor-element-760153c1 elementor-widget elementor-widget-text-editor">
                  <div class="elementor-widget-container">
                    <div class="elementor-element elementor-element-74b033eb elementor-widget elementor-widget-text-editor">
                      <div class="elementor-widget-container"></div>
                    </div>
                  </div>
                </div>
                <div class="elementor-element elementor-element-6ed05fb3 elementor-tablet-align-center elementor-widget elementor-widget-button">
                  <div class="elementor-widget-container">
                    <div class="elementor-button-wrapper">
                      <a class="elementor-button elementor-button-link elementor-size-sm" href="http://chat.bielik.ai">
                        <span class="elementor-button-content-wrapper">
                          <span class="elementor-button-text">Porozmawiaj z Bielikiem</span>
                        </span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-62901256">
              <div class="elementor-widget-wrap elementor-element-populated">
                <div class="elementor-element elementor-element-456f8c23 elementor-widget__width-initial elementor-widget elementor-widget-image">
                  <div class="elementor-widget-container">
                    <img src="https://bielik.ai/wp-content/uploads/2024/08/image_orzel-768x597.png" class="attachment-medium_large size-medium_large wp-image-287"></img>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="elementor-section elementor-top-section elementor-element elementor-element-50ba09bf elementor-section-boxed elementor-section-height-default elementor-section-height-default">
          <div class="elementor-container elementor-column-gap-default">
            <div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-a535de9">
              <div class="elementor-widget-wrap elementor-element-populated">
                <section class="elementor-section elementor-inner-section elementor-element elementor-element-8ec0b25 elementor-section-full_width elementor-section-height-default elementor-section-height-default">
                  <div class="elementor-container elementor-column-gap-default">
                    <div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-6a6f8687 elementor-invisible">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <div class="elementor-element elementor-element-e0fecbe elementor-widget elementor-widget-image">
                          <div class="elementor-widget-container">
                            <img src="https://bielik.ai/wp-content/uploads/2024/08/image_06-768x768.png" class="attachment-medium_large size-medium_large wp-image-212"></img>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="elementor-column elementor-col-66 elementor-inner-column elementor-element elementor-element-2320fe0b elementor-invisible">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <div class="elementor-element elementor-element-7a98438a elementor-widget elementor-widget-heading">
                          <div class="elementor-widget-container">
                            <h2 class="elementor-heading-title elementor-size-default">Efekt pracy społeczności entuzjastów sztucznej inteligencji</h2>
                          </div>
                        </div>
                        <div class="elementor-element elementor-element-20cb7e1f elementor-widget__width-initial elementor-widget elementor-widget-text-editor">
                          <div class="elementor-widget-container">
                            <p>
                              <div></div>
                            </p>
                            <p>Bielik został opracowany na bazie modelu Mistral-7B, jednak znacząco go rozbudowaliśmy, czyniąc go jednym z najpotężniejszych modeli językowych stworzonych w Polsce.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
                <section class="elementor-section elementor-inner-section elementor-element elementor-element-850b9b6 elementor-section-full_width elementor-section-height-default elementor-section-height-default elementor-invisible">
                  <div class="elementor-container elementor-column-gap-default">
                    <div class="elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-2febf3c0">
                      <div class="elementor-widget-wrap"></div>
                    </div>
                    <div class="elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-e6fcfde">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <div class="elementor-element elementor-element-241a8fc elementor-widget elementor-widget-jkit_fun_fact">
                          <div class="elementor-widget-container">
                            <div class="jeg-elementor-kit jkit-fun-fact align-center hover-from-left elementor-animation- jeg_module_20_2_68cfa6624cb42">
                              <div class="fun-fact-inner">
                                <div class="content">
                                  <div class="number-wrapper">
                                    <span class="prefix"></span>
                                    <span class="number">0</span>
                                    <span class="suffix">mld</span>
                                    <div></div>
                                  </div>
                                  <h3 class="title">Parametrów</h3>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="elementor-element elementor-element-61f60fd rm-zero elementor-widget elementor-widget-jkit_fun_fact">
                          <div class="elementor-widget-container">
                            <div class="jeg-elementor-kit jkit-fun-fact align-center hover-from-left elementor-animation- jeg_module_20_3_68cfa6624d43c">
                              <div class="fun-fact-inner">
                                <div class="content">
                                  <div class="number-wrapper">
                                    <span class="prefix"></span>
                                    <span class="number">0</span>
                                    <span class="suffix"></span>
                                    <div></div>
                                  </div>
                                  <h3 class="title">Darmowy model</h3>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-7389f1b3">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <div class="elementor-element elementor-element-6eeeb40d elementor-widget elementor-widget-jkit_fun_fact">
                          <div class="elementor-widget-container">
                            <div class="jeg-elementor-kit jkit-fun-fact align-center hover-from-left elementor-animation- jeg_module_20_4_68cfa6624dc80">
                              <div class="fun-fact-inner">
                                <div class="content">
                                  <div class="number-wrapper">
                                    <span class="prefix"></span>
                                    <span class="number">0</span>
                                    <span class="suffix"></span>
                                  </div>
                                  <h3 class="title">w rankingu Areny</h3>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="elementor-element elementor-element-bcceff1 elementor-widget elementor-widget-jkit_fun_fact">
                          <div class="elementor-widget-container">
                            <div class="jeg-elementor-kit jkit-fun-fact align-center hover-from-left elementor-animation- jeg_module_20_5_68cfa6624e4bc">
                              <div class="fun-fact-inner">
                                <div class="content">
                                  <div class="number-wrapper">
                                    <span class="prefix"></span>
                                    <span class="number">0</span>
                                    <span class="suffix">tys</span>
                                    <div></div>
                                  </div>
                                  <h3 class="title">Kontekst</h3>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-b9d3591">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <a class="elementor-element elementor-element-a13a36a link-container e-flex e-con-boxed e-con e-parent" href="https://huggingface.co/speakleash">
                          <div class="e-con-inner">
                            <div class="elementor-element elementor-element-813e5c7 without-number elementor-widget elementor-widget-jkit_fun_fact">
                              <div class="elementor-widget-container">
                                <div class="jeg-elementor-kit jkit-fun-fact align-center hover-from-left elementor-animation- jeg_module_20_6_68cfa6624eccd">
                                  <div class="fun-fact-inner">
                                    <div class="icon elementor-animation-">
                                      <div></div>
                                    </div>
                                    <div class="content">
                                      <div class="number-wrapper">
                                        <span class="prefix"></span>
                                        <span class="number">0</span>
                                        <span class="suffix"></span>
                                      </div>
                                      <h2 class="title">Dostępny na Hugging Face</h2>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </a>
                        <a class="elementor-element elementor-element-89aacc0 link-container e-flex e-con-boxed e-con e-parent" href="https://arena.speakleash.org.pl/">
                          <div class="e-con-inner">
                            <div class="elementor-element elementor-element-55e79f7 without-number elementor-widget elementor-widget-jkit_fun_fact">
                              <div class="elementor-widget-container">
                                <div class="jeg-elementor-kit jkit-fun-fact align-center hover-from-left elementor-animation- jeg_module_20_7_68cfa6624ff9d">
                                  <div class="fun-fact-inner">
                                    <div class="icon elementor-animation-">
                                      <img src="https://bielik.ai/wp-content/uploads/2024/08/rsz_1swords256x256_1.png" class="attachment-thumbnail size-thumbnail"></img>
                                    </div>
                                    <div class="content">
                                      <div class="number-wrapper">
                                        <span class="prefix"></span>
                                        <span class="number">0</span>
                                        <span class="suffix"></span>
                                      </div>
                                      <h2 class="title">Chat Arena Porównaj modele</h2>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </a>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>
        </section>
        <section class="elementor-section elementor-top-section elementor-element elementor-element-77176f31 elementor-section-boxed elementor-section-height-default elementor-section-height-default">
          <div class="elementor-container elementor-column-gap-default">
            <div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-74297053">
              <div class="elementor-widget-wrap elementor-element-populated">
                <section class="elementor-section elementor-inner-section elementor-element elementor-element-1b6fef6c elementor-section-full_width elementor-hidden-desktop elementor-hidden-tablet elementor-hidden-mobile elementor-section-height-default elementor-section-height-default">
                  <div class="elementor-container elementor-column-gap-default">
                    <div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-5069c10a elementor-invisible">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <div class="elementor-element elementor-element-663a5955 jkit-equal-height-enable elementor-hidden-desktop elementor-hidden-tablet elementor-hidden-mobile elementor-widget elementor-widget-jkit_image_box">
                          <div class="elementor-widget-container">
                            <div class="jeg-elementor-kit jkit-image-box style-default elementor-animation- jeg_module_20_8_68cfa6625317e">
                              <div class="image-box-header elementor-animation-"></div>
                              <div class="image-box-body">
                                <div class="body-inner">
                                  <h3 class="body-title icon-position-before">Bezpieczeństwo i prywatnosć</h3>
                                  <div class="body-description">
                                    <p>Nasze projekty opierają się na zasadach open-source i open-science, co pozwala na transparentność oraz szeroką współpracę z globalną społecznością badawczą i technologiczną​​.</p>
                                  </div>
                                  <div class="body-button"></div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="elementor-element elementor-element-235049a0 elementor-widget__width-auto elementor-widget elementor-widget-image">
                          <div class="elementor-widget-container">
                            <img src="https://bielik.ai/wp-content/uploads/2024/08/Group-27.png" class="attachment-full size-full wp-image-27"></img>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-64dd2c8f elementor-invisible">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <div class="elementor-element elementor-element-65328c75 jkit-equal-height-enable elementor-widget__width-initial elementor-hidden-desktop elementor-hidden-tablet elementor-hidden-mobile elementor-widget elementor-widget-jkit_image_box">
                          <div class="elementor-widget-container">
                            <div class="jeg-elementor-kit jkit-image-box style-default elementor-animation- jeg_module_20_9_68cfa66253b3c">
                              <div class="image-box-header elementor-animation-"></div>
                              <div class="image-box-body">
                                <div class="body-inner">
                                  <h3 class="body-title icon-position-before">Koszty i skalowalność</h3>
                                  <div class="body-description">
                                    <p>Lokalny LLM może być tańszy do wdrożenia i utrzymania niż korzystanie z usług takich jak OpenAI. Ponadto, opłacalność stosowania lokalnego modelu rośnie ze skalą jego wykorzystania, co jest kluczowe dla firm przetwarzających duże ilości danych lub obsługujących liczne zapytania.</p>
                                  </div>
                                  <div class="body-button"></div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="elementor-element elementor-element-49b8ed59 elementor-widget__width-auto elementor-hidden-desktop elementor-hidden-tablet elementor-hidden-mobile elementor-widget elementor-widget-image">
                          <div class="elementor-widget-container">
                            <img src="https://bielik.ai/wp-content/uploads/2024/08/Group-30.png" class="attachment-full size-full wp-image-28"></img>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-aee072d elementor-invisible">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <div class="elementor-element elementor-element-6c33ef7 jkit-equal-height-enable elementor-hidden-desktop elementor-hidden-tablet elementor-hidden-mobile elementor-widget elementor-widget-jkit_image_box">
                          <div class="elementor-widget-container">
                            <div class="jeg-elementor-kit jkit-image-box style-default elementor-animation- jeg_module_20_10_68cfa662548bc">
                              <div class="image-box-header elementor-animation-"></div>
                              <div class="image-box-body">
                                <div class="body-inner">
                                  <h3 class="body-title icon-position-before">Ekosystem i Społeczność</h3>
                                  <div class="body-description">
                                    <p>Wzmacnianie i rozwój polskiego ekosystemu sztucznej inteligencji oraz dbanie o aktywną i zaangażowaną społeczność.</p>
                                    <p>Wspieramy rozwój umiejętności wśród programistów, badaczy i entuzjastów AI poprzez otwartą wymianę wiedzy oraz narzędzi</p>
                                  </div>
                                  <div class="body-button"></div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="elementor-element elementor-element-38f1d65a elementor-widget__width-auto elementor-widget elementor-widget-image">
                          <div class="elementor-widget-container">
                            <img src="https://bielik.ai/wp-content/uploads/2024/08/Group-23.png" class="attachment-full size-full wp-image-29"></img>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>
        </section>
        <section class="elementor-section elementor-top-section elementor-element elementor-element-6c22b27a elementor-section-boxed elementor-section-height-default elementor-section-height-default">
          <div class="elementor-container elementor-column-gap-default">
            <div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-10fcde95">
              <div class="elementor-widget-wrap elementor-element-populated">
                <section class="elementor-section elementor-inner-section elementor-element elementor-element-7ebff4f6 elementor-section-full_width elementor-section-height-default elementor-section-height-default">
                  <div class="elementor-container elementor-column-gap-default">
                    <div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-7fc0fb39">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <div class="elementor-element elementor-element-651abbb4 jkit-equal-height-disable elementor-invisible elementor-widget elementor-widget-jkit_icon_box">
                          <div class="elementor-widget-container">
                            <div class="jeg-elementor-kit jkit-icon-box icon-position-left elementor-animation- jeg_module_20_11_68cfa66259642">
                              <a href="mailto:biuro@speakleash.org.pl" class="icon-box-link">
                                <div class="jkit-icon-box-wrapper hover-from-left">
                                  <div class="icon-box icon-box-header elementor-animation-">
                                    <div class="icon style-color">
                                      <div></div>
                                    </div>
                                  </div>
                                  <div class="icon-box icon-box-body">
                                    <h2 class="title">Email</h2>
                                    <p class="icon-box-description">biuro@speakleash.org.pl</p>
                                  </div>
                                </div>
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-239cae2c">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <div class="elementor-element elementor-element-7bcbd3b0 elementor-shape-circle e-grid-align-right elementor-grid-tablet-2 e-grid-align-mobile-center elementor-grid-mobile-1 elementor-grid-0 elementor-widget elementor-widget-social-icons">
                          <div class="elementor-widget-container">
                            <div class="elementor-social-icons-wrapper elementor-grid">
                              <span class="elementor-grid-item">
                                <a class="elementor-icon elementor-social-icon elementor-social-icon-jki-discord elementor-repeater-item-a5e322d" href="https://discord.com/invite/ZJwCMrxwT7">
                                  <span class="elementor-screen-only">Jki-discord</span>
                                  <div></div>
                                </a>
                              </span>
                              <span class="elementor-grid-item">
                                <a class="elementor-icon elementor-social-icon elementor-social-icon-linkedin elementor-repeater-item-1bb6345" href="https://www.linkedin.com/company/speakleash/">
                                  <span class="elementor-screen-only">Linkedin</span>
                                  <div></div>
                                </a>
                              </span>
                              <span class="elementor-grid-item">
                                <a class="elementor-icon elementor-social-icon elementor-social-icon-github elementor-repeater-item-47e5f5e" href="https://github.com/speakleash">
                                  <span class="elementor-screen-only">Github</span>
                                  <div></div>
                                </a>
                              </span>
                              <span class="elementor-grid-item">
                                <a class="elementor-icon elementor-social-icon elementor-social-icon-x-twitter elementor-repeater-item-abbbcbb" href="https://x.com/Speak_Leash">
                                  <span class="elementor-screen-only">X-twitter</span>
                                  <div></div>
                                </a>
                              </span>
                              <span class="elementor-grid-item">
                                <a class="elementor-icon elementor-social-icon elementor-social-icon-facebook elementor-repeater-item-e76b3c6" href="https://www.facebook.com/Speakleash/">
                                  <span class="elementor-screen-only">Facebook</span>
                                  <div></div>
                                </a>
                              </span>
                              <span class="elementor-grid-item">
                                <a class="elementor-icon elementor-social-icon elementor-social-icon- elementor-repeater-item-9f2ad43" href="https://huggingface.co/speakleash">
                                  <span class="elementor-screen-only"></span>
                                  <div></div>
                                </a>
                              </span>
                              <span class="elementor-grid-item">
                                <a class="elementor-icon elementor-social-icon elementor-social-icon-envelope elementor-repeater-item-0f366f0" href="mailto:team@speakleash.org">
                                  <span class="elementor-screen-only">Envelope</span>
                                  <div></div>
                                </a>
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
                <div class="elementor-element elementor-element-5f087443 elementor-widget-divider--view-line elementor-widget elementor-widget-divider">
                  <div class="elementor-widget-container">
                    <div class="elementor-divider">
                      <span class="elementor-divider-separator"></span>
                    </div>
                  </div>
                </div>
                <section class="elementor-section elementor-inner-section elementor-element elementor-element-80b265d elementor-section-full_width elementor-reverse-mobile elementor-section-height-default elementor-section-height-default">
                  <div class="elementor-container elementor-column-gap-default">
                    <div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-a407af0">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <div class="elementor-element elementor-element-1211840a elementor-widget elementor-widget-text-editor">
                          <div class="elementor-widget-container">
                            <p>©
2025 Bielik.ai | Wszelkie prawa zastrzeżone</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-1c4b2b1">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <div class="elementor-element elementor-element-257189f elementor-widget__width-initial elementor-widget elementor-widget-image">
                          <div class="elementor-widget-container">
                            <a href="https://www.cyfronet.pl/">
                              <img src="https://bielik.ai/wp-content/uploads/2024/08/CYFRONET_1-1024x488.png" class="attachment-large size-large wp-image-208"></img>
                            </a>
                          </div>
                        </div>
                        <div class="elementor-element elementor-element-369b5234 elementor-widget__width-initial elementor-widget elementor-widget-image">
                          <div class="elementor-widget-container">
                            <a href="https://speakleash.org/">
                              <img src="https://bielik.ai/wp-content/uploads/2024/08/speakleash_logo_2-Copy-modified.png" class="attachment-full size-full wp-image-207"></img>
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-29392716">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <div class="elementor-element elementor-element-e468630 elementor-icon-list--layout-inline elementor-align-right elementor-mobile-align-center elementor-tablet-align-right elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list">
                          <div class="elementor-widget-container">
                            <ul class="elementor-icon-list-items elementor-inline-items">
                              <li class="elementor-icon-list-item elementor-inline-item">
                                <a href="/terms">
                                  <span class="elementor-icon-list-text">Warunki użytkowania modelu</span>
                                </a>
                              </li>
                              <li class="elementor-icon-list-item elementor-inline-item">
                                <a href="/polityka-prywatnosci">
                                  <span class="elementor-icon-list-text">Polityka Prywatności</span>
                                </a>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
                <section class="elementor-section elementor-inner-section elementor-element elementor-element-bbf1163 elementor-section-full_width elementor-reverse-mobile elementor-section-height-default elementor-section-height-default">
                  <div class="elementor-container elementor-column-gap-default">
                    <div class="elementor-column elementor-col-100 elementor-inner-column elementor-element elementor-element-fc8469d">
                      <div class="elementor-widget-wrap elementor-element-populated">
                        <div class="elementor-element elementor-element-e28a1a3 elementor-widget-divider--view-line elementor-widget elementor-widget-divider">
                          <div class="elementor-widget-container">
                            <div class="elementor-divider">
                              <span class="elementor-divider-separator"></span>
                            </div>
                          </div>
                        </div>
                        <div class="elementor-element elementor-element-8fb2f0e elementor-widget elementor-widget-heading">
                          <div class="elementor-widget-container">
                            <h2 class="elementor-heading-title elementor-size-default">Partnerzy i sponsorzy</h2>
                          </div>
                        </div>
                        <div class="elementor-element elementor-element-50c4959 elementor-widget elementor-widget-shortcode">
                          <div class="elementor-widget-container">
                            <div class="elementor-shortcode">
                              <div class="rt-container-fluid rt-wpls" id="rt-container-1280752518">
                                <div class="rt-row grid-layout">
                                  <div class="rt-col-md-3 rt-col-sm-6 rt-col-xs-12">
                                    <div>
                                      <div class="single-logo-container">
                                        <a href="https://deviniti.com">
                                          <img src="https://bielik.ai/wp-content/uploads/2025/01/deviniti-logo-footer.svg" class="wls-logo" alt="DEVINITI" title="Deviniti"></img>
                                        </a>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </main>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Bielikai',
  setup() {
    return {};
  }
});
</script>

<style scoped>
.rect-element-0 {
  stroke: none;
  stroke-width: 1;
  stroke-dasharray: none;
  stroke-linecap: butt;
  stroke-dashoffset: 0;
  stroke-linejoin: miter;
  stroke-miterlimit: 4;
  fill: rgb(255,255,255);
  fill-rule: nonzero;
  opacity: 1;
  visibility: hidden;
}
.path-element-2 {
  stroke: none;
  stroke-width: 1;
  stroke-dasharray: none;
  stroke-linecap: butt;
  stroke-dashoffset: 0;
  stroke-linejoin: miter;
  stroke-miterlimit: 4;
  fill: rgb(0,0,0);
  fill-rule: nonzero;
  opacity: 1;
}
.path-element-5 {
  stroke: none;
  stroke-width: 1;
  stroke-dasharray: none;
  stroke-linecap: butt;
  stroke-dashoffset: 0;
  stroke-linejoin: miter;
  stroke-miterlimit: 4;
  fill: rgb(0,0,0);
  fill-rule: evenodd;
  opacity: 1;
}
.path-element-12 {
  stroke: none;
  stroke-width: 1;
  stroke-dasharray: none;
  stroke-linecap: butt;
  stroke-dashoffset: 0;
  stroke-linejoin: miter;
  stroke-miterlimit: 4;
  fill: rgb(255,255,255);
  fill-rule: nonzero;
  opacity: 1;
}
.path-element-15 {
  stroke: none;
  stroke-width: 1;
  stroke-dasharray: none;
  stroke-linecap: butt;
  stroke-dashoffset: 0;
  stroke-linejoin: miter;
  stroke-miterlimit: 4;
  fill: rgb(255,255,255);
  fill-rule: evenodd;
  opacity: 1;
}
.wp-block-file--button {
  background:#32373c;
  color:#fff;
  text-decoration:none;
}
.is-layout-flex {
  flex-wrap: wrap;
  align-items: center;
}
.has-black-color {
  color: var(--wp--preset--color--black) !important;
}
.has-cyan-bluish-gray-color {
  color: var(--wp--preset--color--cyan-bluish-gray) !important;
}
.has-white-color {
  color: var(--wp--preset--color--white) !important;
}
.has-pale-pink-color {
  color: var(--wp--preset--color--pale-pink) !important;
}
.has-vivid-red-color {
  color: var(--wp--preset--color--vivid-red) !important;
}
.has-luminous-vivid-orange-color {
  color: var(--wp--preset--color--luminous-vivid-orange) !important;
}
.has-luminous-vivid-amber-color {
  color: var(--wp--preset--color--luminous-vivid-amber) !important;
}
.has-light-green-cyan-color {
  color: var(--wp--preset--color--light-green-cyan) !important;
}
.has-vivid-green-cyan-color {
  color: var(--wp--preset--color--vivid-green-cyan) !important;
}
.has-pale-cyan-blue-color {
  color: var(--wp--preset--color--pale-cyan-blue) !important;
}
.has-vivid-cyan-blue-color {
  color: var(--wp--preset--color--vivid-cyan-blue) !important;
}
.has-vivid-purple-color {
  color: var(--wp--preset--color--vivid-purple) !important;
}
.has-black-background-color {
  background-color: var(--wp--preset--color--black) !important;
}
.has-cyan-bluish-gray-background-color {
  background-color: var(--wp--preset--color--cyan-bluish-gray) !important;
}
.has-white-background-color {
  background-color: var(--wp--preset--color--white) !important;
}
.has-pale-pink-background-color {
  background-color: var(--wp--preset--color--pale-pink) !important;
}
.has-vivid-red-background-color {
  background-color: var(--wp--preset--color--vivid-red) !important;
}
.has-luminous-vivid-orange-background-color {
  background-color: var(--wp--preset--color--luminous-vivid-orange) !important;
}
.has-luminous-vivid-amber-background-color {
  background-color: var(--wp--preset--color--luminous-vivid-amber) !important;
}
.has-light-green-cyan-background-color {
  background-color: var(--wp--preset--color--light-green-cyan) !important;
}
.has-vivid-green-cyan-background-color {
  background-color: var(--wp--preset--color--vivid-green-cyan) !important;
}
.has-pale-cyan-blue-background-color {
  background-color: var(--wp--preset--color--pale-cyan-blue) !important;
}
.has-vivid-cyan-blue-background-color {
  background-color: var(--wp--preset--color--vivid-cyan-blue) !important;
}
.has-vivid-purple-background-color {
  background-color: var(--wp--preset--color--vivid-purple) !important;
}
.has-black-border-color {
  border-color: var(--wp--preset--color--black) !important;
}
.has-cyan-bluish-gray-border-color {
  border-color: var(--wp--preset--color--cyan-bluish-gray) !important;
}
.has-white-border-color {
  border-color: var(--wp--preset--color--white) !important;
}
.has-pale-pink-border-color {
  border-color: var(--wp--preset--color--pale-pink) !important;
}
.has-vivid-red-border-color {
  border-color: var(--wp--preset--color--vivid-red) !important;
}
.has-luminous-vivid-orange-border-color {
  border-color: var(--wp--preset--color--luminous-vivid-orange) !important;
}
.has-luminous-vivid-amber-border-color {
  border-color: var(--wp--preset--color--luminous-vivid-amber) !important;
}
.has-light-green-cyan-border-color {
  border-color: var(--wp--preset--color--light-green-cyan) !important;
}
.has-vivid-green-cyan-border-color {
  border-color: var(--wp--preset--color--vivid-green-cyan) !important;
}
.has-pale-cyan-blue-border-color {
  border-color: var(--wp--preset--color--pale-cyan-blue) !important;
}
.has-vivid-cyan-blue-border-color {
  border-color: var(--wp--preset--color--vivid-cyan-blue) !important;
}
.has-vivid-purple-border-color {
  border-color: var(--wp--preset--color--vivid-purple) !important;
}
.has-vivid-cyan-blue-to-vivid-purple-gradient-background {
  background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;
}
.has-light-green-cyan-to-vivid-green-cyan-gradient-background {
  background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;
}
.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background {
  background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;
}
.has-luminous-vivid-orange-to-vivid-red-gradient-background {
  background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important;
}
.has-very-light-gray-to-cyan-bluish-gray-gradient-background {
  background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important;
}
.has-cool-to-warm-spectrum-gradient-background {
  background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important;
}
.has-blush-light-purple-gradient-background {
  background: var(--wp--preset--gradient--blush-light-purple) !important;
}
.has-blush-bordeaux-gradient-background {
  background: var(--wp--preset--gradient--blush-bordeaux) !important;
}
.has-luminous-dusk-gradient-background {
  background: var(--wp--preset--gradient--luminous-dusk) !important;
}
.has-pale-ocean-gradient-background {
  background: var(--wp--preset--gradient--pale-ocean) !important;
}
.has-electric-grass-gradient-background {
  background: var(--wp--preset--gradient--electric-grass) !important;
}
.has-midnight-gradient-background {
  background: var(--wp--preset--gradient--midnight) !important;
}
.has-small-font-size {
  font-size: var(--wp--preset--font-size--small) !important;
}
.has-medium-font-size {
  font-size: var(--wp--preset--font-size--medium) !important;
}
.has-large-font-size {
  font-size: var(--wp--preset--font-size--large) !important;
}
.has-x-large-font-size {
  font-size: var(--wp--preset--font-size--x-large) !important;
}
.page-content-a {
  text-decoration: none;
}
</style>